// Hand-written wrappers for functions requiring pointer/array params.
// These cannot be auto-generated by generate.R.

#include "raylibr.h"

// [[Rcpp::plugins(cpp11)]]

// --- Camera mutation ---------------------------------------------------------

// [[Rcpp::export]]
void update_camera_(SEXP camera_ptr, int mode) {
  XPtr<Camera3D> cam(camera_ptr);
  UpdateCamera(cam.get(), mode);
}

// [[Rcpp::export]]
void update_camera_pro_(SEXP camera_ptr, Vector3 movement, Vector3 rotation, float zoom) {
  XPtr<Camera3D> cam(camera_ptr);
  UpdateCameraPro(cam.get(), movement, rotation, zoom);
}

// --- Vector2 array helpers ---------------------------------------------------

static std::vector<Vector2> matrix_to_vec2(Rcpp::NumericMatrix mat) {
  int n = mat.nrow();
  std::vector<Vector2> pts(n);
  for (int i = 0; i < n; i++) {
    pts[i] = {(float)mat(i, 0), (float)mat(i, 1)};
  }
  return pts;
}

// [[Rcpp::export]]
void draw_line_strip_(Rcpp::NumericMatrix points, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawLineStrip(pts.data(), pts.size(), color);
}

// [[Rcpp::export]]
void draw_triangle_fan_(Rcpp::NumericMatrix points, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawTriangleFan(pts.data(), pts.size(), color);
}

// [[Rcpp::export]]
void draw_triangle_strip_(Rcpp::NumericMatrix points, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawTriangleStrip(pts.data(), pts.size(), color);
}

// [[Rcpp::export]]
void draw_spline_linear_(Rcpp::NumericMatrix points, float thick, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawSplineLinear(pts.data(), pts.size(), thick, color);
}

// [[Rcpp::export]]
void draw_spline_basis_(Rcpp::NumericMatrix points, float thick, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawSplineBasis(pts.data(), pts.size(), thick, color);
}

// [[Rcpp::export]]
void draw_spline_catmull_rom_(Rcpp::NumericMatrix points, float thick, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawSplineCatmullRom(pts.data(), pts.size(), thick, color);
}

// [[Rcpp::export]]
void draw_spline_bezier_quadratic_(Rcpp::NumericMatrix points, float thick, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawSplineBezierQuadratic(pts.data(), pts.size(), thick, color);
}

// [[Rcpp::export]]
void draw_spline_bezier_cubic_(Rcpp::NumericMatrix points, float thick, Color color) {
  auto pts = matrix_to_vec2(points);
  DrawSplineBezierCubic(pts.data(), pts.size(), thick, color);
}

// --- Vector3 array -----------------------------------------------------------

// [[Rcpp::export]]
void draw_triangle_strip_3d_(Rcpp::NumericMatrix points, Color color) {
  int n = points.nrow();
  std::vector<Vector3> pts(n);
  for (int i = 0; i < n; i++) {
    pts[i] = {(float)points(i, 0), (float)points(i, 1), (float)points(i, 2)};
  }
  DrawTriangleStrip3D(pts.data(), pts.size(), color);
}

// --- Wave mutation -----------------------------------------------------------

// [[Rcpp::export]]
void wave_crop_(SEXP wave_ptr, int init_frame, int final_frame) {
  XPtr<Wave> w(wave_ptr);
  WaveCrop(w.get(), init_frame, final_frame);
}

// [[Rcpp::export]]
void wave_format_(SEXP wave_ptr, int sample_rate, int sample_size, int channels) {
  XPtr<Wave> w(wave_ptr);
  WaveFormat(w.get(), sample_rate, sample_size, channels);
}

// --- Material/Model/Mesh mutation --------------------------------------------

// [[Rcpp::export]]
void set_model_texture_(SEXP model_ptr, int material_id, int map_type, Texture2D texture) {
  XPtr<Model> m(model_ptr);
  m->materials[material_id].maps[map_type].texture = texture;
}

// [[Rcpp::export]]
void set_material_texture_(SEXP material_ptr, int map_type, Texture2D texture) {
  XPtr<Material> mat(material_ptr);
  SetMaterialTexture(mat.get(), map_type, texture);
}

// [[Rcpp::export]]
void set_model_mesh_material_(SEXP model_ptr, int mesh_id, int material_id) {
  XPtr<Model> m(model_ptr);
  SetModelMeshMaterial(m.get(), mesh_id, material_id);
}

// [[Rcpp::export]]
void gen_mesh_tangents_(SEXP mesh_ptr) {
  XPtr<Mesh> m(mesh_ptr);
  GenMeshTangents(m.get());
}

// [[Rcpp::export]]
void upload_mesh_(SEXP mesh_ptr, bool dynamic) {
  XPtr<Mesh> m(mesh_ptr);
  UploadMesh(m.get(), dynamic);
}

// --- Image drawing with mutation ---------------------------------------------

// [[Rcpp::export]]
void image_draw_line_ex_(SEXP dst_ptr, Vector2 start, Vector2 end, int thick, Color color) {
  XPtr<Image> img(dst_ptr);
  ImageDrawLineEx(img.get(), start, end, thick, color);
}

// [[Rcpp::export]]
void image_draw_triangle_(SEXP dst_ptr, Vector2 v1, Vector2 v2, Vector2 v3, Color color) {
  XPtr<Image> img(dst_ptr);
  ImageDrawTriangle(img.get(), v1, v2, v3, color);
}

// --- Matrix array function ---------------------------------------------------

static RaylibMatrix sexp_to_matrix(SEXP x) {
  Rcpp::NumericMatrix m(x);
  return RaylibMatrix {
    (float)m(0,0), (float)m(1,0), (float)m(2,0), (float)m(3,0),
    (float)m(0,1), (float)m(1,1), (float)m(2,1), (float)m(3,1),
    (float)m(0,2), (float)m(1,2), (float)m(2,2), (float)m(3,2),
    (float)m(0,3), (float)m(1,3), (float)m(2,3), (float)m(3,3)
  };
}

// [[Rcpp::export]]
void draw_mesh_instanced_(Mesh mesh, Material material, Rcpp::List transforms) {
  int n = transforms.size();
  std::vector<RaylibMatrix> mats(n);
  for (int i = 0; i < n; i++) {
    mats[i] = sexp_to_matrix(transforms[i]);
  }
  DrawMeshInstanced(mesh, material, mats.data(), n);
}

// --- raymath output-pointer functions ----------------------------------------

static Rcpp::NumericVector vec3_to_r(Vector3 v) {
  Rcpp::NumericVector r(3);
  r[0] = v.x; r[1] = v.y; r[2] = v.z;
  r.names() = Rcpp::CharacterVector::create("x", "y", "z");
  return r;
}

static Rcpp::NumericVector vec4_to_r(Vector4 v) {
  Rcpp::NumericVector r(4);
  r[0] = v.x; r[1] = v.y; r[2] = v.z; r[3] = v.w;
  r.names() = Rcpp::CharacterVector::create("x", "y", "z", "w");
  return r;
}

// [[Rcpp::export]]
Rcpp::List vector3_ortho_normalize_(Vector3 v1, Vector3 v2) {
  Vector3OrthoNormalize(&v1, &v2);
  return Rcpp::List::create(Rcpp::Named("v1") = vec3_to_r(v1), Rcpp::Named("v2") = vec3_to_r(v2));
}

// [[Rcpp::export]]
Rcpp::List quaternion_to_axis_angle_(Vector4 q) {
  Vector3 axis;
  float angle;
  QuaternionToAxisAngle(q, &axis, &angle);
  return Rcpp::List::create(Rcpp::Named("axis") = vec3_to_r(axis), Rcpp::Named("angle") = angle);
}

// [[Rcpp::export]]
Rcpp::List matrix_decompose_(RaylibMatrix mat) {
  Vector3 translation, scale;
  Vector4 rotation;
  MatrixDecompose(mat, &translation, &rotation, &scale);
  return Rcpp::List::create(
    Rcpp::Named("translation") = vec3_to_r(translation),
    Rcpp::Named("rotation") = vec4_to_r(rotation),
    Rcpp::Named("scale") = vec3_to_r(scale)
  );
}

// --- rcamera functions -------------------------------------------------------

// [[Rcpp::export]]
Vector3 get_camera_forward_(SEXP camera_ptr) {
  XPtr<Camera3D> cam(camera_ptr);
  return GetCameraForward(cam.get());
}

// [[Rcpp::export]]
Vector3 get_camera_up_(SEXP camera_ptr) {
  XPtr<Camera3D> cam(camera_ptr);
  return GetCameraUp(cam.get());
}

// [[Rcpp::export]]
Vector3 get_camera_right_(SEXP camera_ptr) {
  XPtr<Camera3D> cam(camera_ptr);
  return GetCameraRight(cam.get());
}

// [[Rcpp::export]]
RaylibMatrix get_camera_view_matrix_(SEXP camera_ptr) {
  XPtr<Camera3D> cam(camera_ptr);
  return GetCameraViewMatrix(cam.get());
}

// [[Rcpp::export]]
RaylibMatrix get_camera_projection_matrix_(SEXP camera_ptr, float aspect) {
  XPtr<Camera3D> cam(camera_ptr);
  return GetCameraProjectionMatrix(cam.get(), aspect);
}

// [[Rcpp::export]]
void camera_move_forward_(SEXP camera_ptr, float distance, bool move_in_world_plane) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraMoveForward(cam.get(), distance, move_in_world_plane);
}

// [[Rcpp::export]]
void camera_move_up_(SEXP camera_ptr, float distance) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraMoveUp(cam.get(), distance);
}

// [[Rcpp::export]]
void camera_move_right_(SEXP camera_ptr, float distance, bool move_in_world_plane) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraMoveRight(cam.get(), distance, move_in_world_plane);
}

// [[Rcpp::export]]
void camera_move_to_target_(SEXP camera_ptr, float delta) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraMoveToTarget(cam.get(), delta);
}

// [[Rcpp::export]]
void camera_yaw_(SEXP camera_ptr, float angle, bool rotate_around_target) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraYaw(cam.get(), angle, rotate_around_target);
}

// [[Rcpp::export]]
void camera_pitch_(SEXP camera_ptr, float angle, bool lock_view, bool rotate_around_target, bool rotate_up) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraPitch(cam.get(), angle, lock_view, rotate_around_target, rotate_up);
}

// [[Rcpp::export]]
void camera_roll_(SEXP camera_ptr, float angle) {
  XPtr<Camera3D> cam(camera_ptr);
  CameraRoll(cam.get(), angle);
}

// --- Shader value helpers ----------------------------------------------------

// [[Rcpp::export]]
void set_shader_value_float_(Shader shader, int loc_index, float value) {
  SetShaderValue(shader, loc_index, &value, SHADER_UNIFORM_FLOAT);
}

// [[Rcpp::export]]
void set_shader_value_vector_2_(Shader shader, int loc_index, Vector2 value) {
  SetShaderValue(shader, loc_index, &value, SHADER_UNIFORM_VEC2);
}

// [[Rcpp::export]]
void set_shader_value_vector_3_(Shader shader, int loc_index, Vector3 value) {
  SetShaderValue(shader, loc_index, &value, SHADER_UNIFORM_VEC3);
}

// [[Rcpp::export]]
void set_shader_value_vector_4_(Shader shader, int loc_index, Vector4 value) {
  SetShaderValue(shader, loc_index, &value, SHADER_UNIFORM_VEC4);
}

// --- Font loading ------------------------------------------------------------

// [[Rcpp::export]]
Font load_font_ex_(const char* file_name, int font_size) {
  return LoadFontEx(file_name, font_size, NULL, 0);
}

// --- raygui manual wrappers --------------------------------------------------

static Rcpp::NumericVector vec2_to_r(Vector2 v) {
  Rcpp::NumericVector r(2);
  r[0] = v.x; r[1] = v.y;
  r.names() = Rcpp::CharacterVector::create("x", "y");
  return r;
}

static Rcpp::NumericVector rect_to_r(Rectangle r) {
  Rcpp::NumericVector rv(4);
  rv[0] = r.x; rv[1] = r.y; rv[2] = r.width; rv[3] = r.height;
  rv.names() = Rcpp::CharacterVector::create("x", "y", "width", "height");
  rv.attr("class") = "raylibr_rectangle";
  return rv;
}

// [[Rcpp::export]]
Rcpp::List gui_scroll_panel_(Rectangle bounds, const char* text, Rectangle content,
                              Vector2 scroll, Rectangle view) {
  int result = GuiScrollPanel(bounds, text, content, &scroll, &view);
  return Rcpp::List::create(Rcpp::Named("result") = result,
                            Rcpp::Named("scroll") = vec2_to_r(scroll),
                            Rcpp::Named("view") = rect_to_r(view));
}

// [[Rcpp::export]]
Rcpp::List gui_text_box_(Rectangle bounds, std::string text, int text_size, bool edit_mode) {
  std::vector<char> buf(text_size + 1, 0);
  strncpy(buf.data(), text.c_str(), text_size);
  int result = GuiTextBox(bounds, buf.data(), text_size, edit_mode);
  return Rcpp::List::create(Rcpp::Named("result") = result,
                            Rcpp::Named("text") = std::string(buf.data()));
}

// [[Rcpp::export]]
Rcpp::List gui_text_input_box_(Rectangle bounds, const char* title, const char* message,
                                std::string text, int text_size, const char* btn_text,
                                int btn_active, bool secret_view_active) {
  std::vector<char> buf(text_size + 1, 0);
  strncpy(buf.data(), text.c_str(), text_size);
  int result = GuiTextInputBox(bounds, title, message, buf.data(), text_size,
                                btn_text, &btn_active, &secret_view_active);
  return Rcpp::List::create(Rcpp::Named("result") = result,
                            Rcpp::Named("text") = std::string(buf.data()),
                            Rcpp::Named("btn_active") = btn_active,
                            Rcpp::Named("secret_view_active") = secret_view_active);
}

// [[Rcpp::export]]
Rcpp::List gui_value_box_float_(Rectangle bounds, const char* text,
                                 std::string text_value, float value, bool edit_mode) {
  std::vector<char> buf(64, 0);
  strncpy(buf.data(), text_value.c_str(), 63);
  int result = GuiValueBoxFloat(bounds, text, buf.data(), &value, edit_mode);
  return Rcpp::List::create(Rcpp::Named("result") = result,
                            Rcpp::Named("text_value") = std::string(buf.data()),
                            Rcpp::Named("value") = (double)value);
}
