# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Init window
#'
#' Initialize window and OpenGL context.
#'
#' @param width An integer.
#' @param height An integer.
#' @param title A string.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void InitWindow(int width, int height, const char *title);`
#'
#' @export
init_window <- function(width, height, title) {
    invisible(.Call(`_raylibr_init_window`, width, height, title))
}

#' Window should close
#'
#' Check if KEY_ESCAPE pressed or Close icon pressed.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool WindowShouldClose(void);`
#'
#' @export
window_should_close <- function() {
    .Call(`_raylibr_window_should_close`)
}

#' Close window
#'
#' Close window and unload OpenGL context.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void CloseWindow(void);`
#'
#' @export
close_window <- function() {
    invisible(.Call(`_raylibr_close_window`))
}

#' Is window ready
#'
#' Check if window has been initialized successfully.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowReady(void);`
#'
#' @export
is_window_ready <- function() {
    .Call(`_raylibr_is_window_ready`)
}

#' Is window fullscreen
#'
#' Check if window is currently fullscreen.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowFullscreen(void);`
#'
#' @export
is_window_fullscreen <- function() {
    .Call(`_raylibr_is_window_fullscreen`)
}

#' Is window hidden
#'
#' Check if window is currently hidden (only PLATFORM_DESKTOP).
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowHidden(void);`
#'
#' @export
is_window_hidden <- function() {
    .Call(`_raylibr_is_window_hidden`)
}

#' Is window minimized
#'
#' Check if window is currently minimized (only PLATFORM_DESKTOP).
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowMinimized(void);`
#'
#' @export
is_window_minimized <- function() {
    .Call(`_raylibr_is_window_minimized`)
}

#' Is window maximized
#'
#' Check if window is currently maximized (only PLATFORM_DESKTOP).
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowMaximized(void);`
#'
#' @export
is_window_maximized <- function() {
    .Call(`_raylibr_is_window_maximized`)
}

#' Is window focused
#'
#' Check if window is currently focused (only PLATFORM_DESKTOP).
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowFocused(void);`
#'
#' @export
is_window_focused <- function() {
    .Call(`_raylibr_is_window_focused`)
}

#' Is window resized
#'
#' Check if window has been resized last frame.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowResized(void);`
#'
#' @export
is_window_resized <- function() {
    .Call(`_raylibr_is_window_resized`)
}

#' Is window state
#'
#' Check if one specific window flag is enabled.
#'
#' @param flag A non-negative integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsWindowState(unsigned int flag);`
#'
#' @export
is_window_state <- function(flag) {
    .Call(`_raylibr_is_window_state`, flag)
}

#' Set window state
#'
#' Set window configuration state using flags.
#'
#' @param flags A non-negative integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowState(unsigned int flags);`
#'
#' @export
set_window_state <- function(flags) {
    invisible(.Call(`_raylibr_set_window_state`, flags))
}

#' Clear window state
#'
#' Clear window configuration state flags.
#'
#' @param flags A non-negative integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ClearWindowState(unsigned int flags);`
#'
#' @export
clear_window_state <- function(flags) {
    invisible(.Call(`_raylibr_clear_window_state`, flags))
}

#' Toggle fullscreen
#'
#' Toggle window state: fullscreen/windowed (only PLATFORM_DESKTOP).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ToggleFullscreen(void);`
#'
#' @export
toggle_fullscreen <- function() {
    invisible(.Call(`_raylibr_toggle_fullscreen`))
}

#' Maximize window
#'
#' Set window state: maximized, if resizable (only PLATFORM_DESKTOP).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void MaximizeWindow(void);`
#'
#' @export
maximize_window <- function() {
    invisible(.Call(`_raylibr_maximize_window`))
}

#' Minimize window
#'
#' Set window state: minimized, if resizable (only PLATFORM_DESKTOP).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void MinimizeWindow(void);`
#'
#' @export
minimize_window <- function() {
    invisible(.Call(`_raylibr_minimize_window`))
}

#' Restore window
#'
#' Set window state: not minimized/maximized (only PLATFORM_DESKTOP).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void RestoreWindow(void);`
#'
#' @export
restore_window <- function() {
    invisible(.Call(`_raylibr_restore_window`))
}

#' Set window icon
#'
#' Set icon for window (only PLATFORM_DESKTOP).
#'
#' @param image A image.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowIcon(Image image);`
#'
#' @export
set_window_icon <- function(image) {
    invisible(.Call(`_raylibr_set_window_icon`, image))
}

#' Set window title
#'
#' Set title for window (only PLATFORM_DESKTOP).
#'
#' @param title A string.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowTitle(const char *title);`
#'
#' @export
set_window_title <- function(title) {
    invisible(.Call(`_raylibr_set_window_title`, title))
}

#' Set window position
#'
#' Set window position on screen (only PLATFORM_DESKTOP).
#'
#' @param x An integer.
#' @param y An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowPosition(int x, int y);`
#'
#' @export
set_window_position <- function(x, y) {
    invisible(.Call(`_raylibr_set_window_position`, x, y))
}

#' Set window monitor
#'
#' Set monitor for the current window (fullscreen mode).
#'
#' @param monitor An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowMonitor(int monitor);`
#'
#' @export
set_window_monitor <- function(monitor) {
    invisible(.Call(`_raylibr_set_window_monitor`, monitor))
}

#' Set window min size
#'
#' Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE).
#'
#' @param width An integer.
#' @param height An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowMinSize(int width, int height);`
#'
#' @export
set_window_min_size <- function(width, height) {
    invisible(.Call(`_raylibr_set_window_min_size`, width, height))
}

#' Set window size
#'
#' Set window dimensions.
#'
#' @param width An integer.
#' @param height An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetWindowSize(int width, int height);`
#'
#' @export
set_window_size <- function(width, height) {
    invisible(.Call(`_raylibr_set_window_size`, width, height))
}

#' Get screen width
#'
#' Get current screen width.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetScreenWidth(void);`
#'
#' @export
get_screen_width <- function() {
    .Call(`_raylibr_get_screen_width`)
}

#' Get screen height
#'
#' Get current screen height.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetScreenHeight(void);`
#'
#' @export
get_screen_height <- function() {
    .Call(`_raylibr_get_screen_height`)
}

#' Get monitor count
#'
#' Get number of connected monitors.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorCount(void);`
#'
#' @export
get_monitor_count <- function() {
    .Call(`_raylibr_get_monitor_count`)
}

#' Get current monitor
#'
#' Get current connected monitor.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetCurrentMonitor(void);`
#'
#' @export
get_current_monitor <- function() {
    .Call(`_raylibr_get_current_monitor`)
}

#' Get monitor position
#'
#' Get specified monitor position.
#'
#' @param monitor An integer.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetMonitorPosition(int monitor);`
#'
#' @export
get_monitor_position <- function(monitor) {
    .Call(`_raylibr_get_monitor_position`, monitor)
}

#' Get monitor width
#'
#' Get specified monitor width (max available by monitor).
#'
#' @param monitor An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorWidth(int monitor);`
#'
#' @export
get_monitor_width <- function(monitor) {
    .Call(`_raylibr_get_monitor_width`, monitor)
}

#' Get monitor height
#'
#' Get specified monitor height (max available by monitor).
#'
#' @param monitor An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorHeight(int monitor);`
#'
#' @export
get_monitor_height <- function(monitor) {
    .Call(`_raylibr_get_monitor_height`, monitor)
}

#' Get monitor physical width
#'
#' Get specified monitor physical width in millimetres.
#'
#' @param monitor An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorPhysicalWidth(int monitor);`
#'
#' @export
get_monitor_physical_width <- function(monitor) {
    .Call(`_raylibr_get_monitor_physical_width`, monitor)
}

#' Get monitor physical height
#'
#' Get specified monitor physical height in millimetres.
#'
#' @param monitor An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorPhysicalHeight(int monitor);`
#'
#' @export
get_monitor_physical_height <- function(monitor) {
    .Call(`_raylibr_get_monitor_physical_height`, monitor)
}

#' Get monitor refresh rate
#'
#' Get specified monitor refresh rate.
#'
#' @param monitor An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMonitorRefreshRate(int monitor);`
#'
#' @export
get_monitor_refresh_rate <- function(monitor) {
    .Call(`_raylibr_get_monitor_refresh_rate`, monitor)
}

#' Get window position
#'
#' Get window position XY on monitor.
#'
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetWindowPosition(void);`
#'
#' @export
get_window_position <- function() {
    .Call(`_raylibr_get_window_position`)
}

#' Get window scale dpi
#'
#' Get window scale DPI factor.
#'
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetWindowScaleDPI(void);`
#'
#' @export
get_window_scale_dpi <- function() {
    .Call(`_raylibr_get_window_scale_dpi`)
}

#' Get monitor name
#'
#' Get the human-readable, UTF-8 encoded name of the primary monitor.
#'
#' @param monitor An integer.
#' @return A string
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `const char *GetMonitorName(int monitor);`
#'
#' @export
get_monitor_name <- function(monitor) {
    .Call(`_raylibr_get_monitor_name`, monitor)
}

#' Show cursor
#'
#' Shows cursor.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ShowCursor(void);`
#'
#' @export
show_cursor <- function() {
    invisible(.Call(`_raylibr_show_cursor`))
}

#' Hide cursor
#'
#' Hides cursor.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void HideCursor(void);`
#'
#' @export
hide_cursor <- function() {
    invisible(.Call(`_raylibr_hide_cursor`))
}

#' Is cursor hidden
#'
#' Check if cursor is not visible.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsCursorHidden(void);`
#'
#' @export
is_cursor_hidden <- function() {
    .Call(`_raylibr_is_cursor_hidden`)
}

#' Enable cursor
#'
#' Enables cursor (unlock cursor).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void EnableCursor(void);`
#'
#' @export
enable_cursor <- function() {
    invisible(.Call(`_raylibr_enable_cursor`))
}

#' Disable cursor
#'
#' Disables cursor (lock cursor).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DisableCursor(void);`
#'
#' @export
disable_cursor <- function() {
    invisible(.Call(`_raylibr_disable_cursor`))
}

#' Is cursor on screen
#'
#' Check if cursor is on the screen.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsCursorOnScreen(void);`
#'
#' @export
is_cursor_on_screen <- function() {
    .Call(`_raylibr_is_cursor_on_screen`)
}

#' Clear background
#'
#' Set background color (framebuffer clear color).
#'
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ClearBackground(Color color);`
#'
#' @export
clear_background <- function(color) {
    invisible(.Call(`_raylibr_clear_background`, color))
}

#' Begin drawing
#'
#' Setup canvas (framebuffer) to start drawing.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void BeginDrawing(void);`
#'
#' @export
begin_drawing <- function() {
    invisible(.Call(`_raylibr_begin_drawing`))
}

#' End drawing
#'
#' End canvas drawing and swap buffers (double buffering).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void EndDrawing(void);`
#'
#' @export
end_drawing <- function() {
    invisible(.Call(`_raylibr_end_drawing`))
}

#' Begin mode 2d
#'
#' Begin 2D mode with custom camera (2D).
#'
#' @param camera A camera_2d.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void BeginMode2D(Camera2D camera);`
#'
#' @export
begin_mode_2d <- function(camera) {
    invisible(.Call(`_raylibr_begin_mode_2d`, camera))
}

#' End mode 2d
#'
#' Ends 2D mode with custom camera.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void EndMode2D(void);`
#'
#' @export
end_mode_2d <- function() {
    invisible(.Call(`_raylibr_end_mode_2d`))
}

#' Begin mode 3d
#'
#' Begin 3D mode with custom camera (3D).
#'
#' @param camera A camera_3d.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void BeginMode3D(Camera3D camera);`
#'
#' @export
begin_mode_3d <- function(camera) {
    invisible(.Call(`_raylibr_begin_mode_3d`, camera))
}

#' End mode 3d
#'
#' Ends 3D mode and returns to default 2D orthographic mode.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void EndMode3D(void);`
#'
#' @export
end_mode_3d <- function() {
    invisible(.Call(`_raylibr_end_mode_3d`))
}

#' Get camera matrix
#'
#' Get camera transform matrix (view matrix).
#'
#' @param camera A camera_3d.
#' @return A numeric matrix of 4 by 4
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Matrix GetCameraMatrix(Camera camera);`
#'
#' @export
get_camera_matrix <- function(camera) {
    .Call(`_raylibr_get_camera_matrix`, camera)
}

#' Get camera matrix 2d
#'
#' Get camera 2d transform matrix.
#'
#' @param camera A camera_2d.
#' @return A numeric matrix of 4 by 4
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Matrix GetCameraMatrix2D(Camera2D camera);`
#'
#' @export
get_camera_matrix_2d <- function(camera) {
    .Call(`_raylibr_get_camera_matrix_2d`, camera)
}

#' Get world to screen
#'
#' Get the screen space position for a 3d world space position.
#'
#' @param position A numeric vector of length 3.
#' @param camera A camera_3d.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetWorldToScreen(Vector3 position, Camera camera);`
#'
#' @export
get_world_to_screen <- function(position, camera) {
    .Call(`_raylibr_get_world_to_screen`, position, camera)
}

#' Get world to screen ex
#'
#' Get size position for a 3d world space position.
#'
#' @param position A numeric vector of length 3.
#' @param camera A camera_3d.
#' @param width An integer.
#' @param height An integer.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height);`
#'
#' @export
get_world_to_screen_ex <- function(position, camera, width, height) {
    .Call(`_raylibr_get_world_to_screen_ex`, position, camera, width, height)
}

#' Get world to screen 2d
#'
#' Get the screen space position for a 2d camera world space position.
#'
#' @param position A numeric vector of length 2.
#' @param camera A camera_2d.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetWorldToScreen2D(Vector2 position, Camera2D camera);`
#'
#' @export
get_world_to_screen_2d <- function(position, camera) {
    .Call(`_raylibr_get_world_to_screen_2d`, position, camera)
}

#' Get screen to world 2d
#'
#' Get the world space position for a 2d camera screen space position.
#'
#' @param position A numeric vector of length 2.
#' @param camera A camera_2d.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetScreenToWorld2D(Vector2 position, Camera2D camera);`
#'
#' @export
get_screen_to_world_2d <- function(position, camera) {
    .Call(`_raylibr_get_screen_to_world_2d`, position, camera)
}

#' Set target fps
#'
#' Set target FPS (maximum).
#'
#' @param fps An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetTargetFPS(int fps);`
#'
#' @export
set_target_fps <- function(fps) {
    invisible(.Call(`_raylibr_set_target_fps`, fps))
}

#' Get fps
#'
#' Get current FPS.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetFPS(void);`
#'
#' @export
get_fps <- function() {
    .Call(`_raylibr_get_fps`)
}

#' Get frame time
#'
#' Get time in seconds for last frame drawn (delta time).
#'
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float GetFrameTime(void);`
#'
#' @export
get_frame_time <- function() {
    .Call(`_raylibr_get_frame_time`)
}

#' Get time
#'
#' Get elapsed time in seconds since InitWindow().
#'
#' @return A double
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `double GetTime(void);`
#'
#' @export
get_time <- function() {
    .Call(`_raylibr_get_time`)
}

#' Get random value
#'
#' Get a random value between min and max (both included).
#'
#' @param min An integer.
#' @param max An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetRandomValue(int min, int max);`
#'
#' @export
get_random_value <- function(min, max) {
    .Call(`_raylibr_get_random_value`, min, max)
}

#' Take screenshot
#'
#' Takes a screenshot of current screen (filename extension defines format).
#'
#' @param file_name A string.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void TakeScreenshot(const char *fileName);`
#'
#' @export
take_screenshot <- function(file_name) {
    invisible(.Call(`_raylibr_take_screenshot`, file_name))
}

#' Is key pressed
#'
#' Check if a key has been pressed once.
#'
#' @param key An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsKeyPressed(int key);`
#'
#' @export
is_key_pressed <- function(key) {
    .Call(`_raylibr_is_key_pressed`, key)
}

#' Is key down
#'
#' Check if a key is being pressed.
#'
#' @param key An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsKeyDown(int key);`
#'
#' @export
is_key_down <- function(key) {
    .Call(`_raylibr_is_key_down`, key)
}

#' Is key released
#'
#' Check if a key has been released once.
#'
#' @param key An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsKeyReleased(int key);`
#'
#' @export
is_key_released <- function(key) {
    .Call(`_raylibr_is_key_released`, key)
}

#' Is key up
#'
#' Check if a key is NOT being pressed.
#'
#' @param key An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsKeyUp(int key);`
#'
#' @export
is_key_up <- function(key) {
    .Call(`_raylibr_is_key_up`, key)
}

#' Set exit key
#'
#' Set a custom key to exit program (default is ESC).
#'
#' @param key An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetExitKey(int key);`
#'
#' @export
set_exit_key <- function(key) {
    invisible(.Call(`_raylibr_set_exit_key`, key))
}

#' Get key pressed
#'
#' Get key pressed (keycode), call it multiple times for keys queued, returns 0 when the queue is empty.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetKeyPressed(void);`
#'
#' @export
get_key_pressed <- function() {
    .Call(`_raylibr_get_key_pressed`)
}

#' Get char pressed
#'
#' Get char pressed (unicode), call it multiple times for chars queued, returns 0 when the queue is empty.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetCharPressed(void);`
#'
#' @export
get_char_pressed <- function() {
    .Call(`_raylibr_get_char_pressed`)
}

#' Is mouse button pressed
#'
#' Check if a mouse button has been pressed once.
#'
#' @param button An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsMouseButtonPressed(int button);`
#'
#' @export
is_mouse_button_pressed <- function(button) {
    .Call(`_raylibr_is_mouse_button_pressed`, button)
}

#' Is mouse button down
#'
#' Check if a mouse button is being pressed.
#'
#' @param button An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsMouseButtonDown(int button);`
#'
#' @export
is_mouse_button_down <- function(button) {
    .Call(`_raylibr_is_mouse_button_down`, button)
}

#' Is mouse button released
#'
#' Check if a mouse button has been released once.
#'
#' @param button An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsMouseButtonReleased(int button);`
#'
#' @export
is_mouse_button_released <- function(button) {
    .Call(`_raylibr_is_mouse_button_released`, button)
}

#' Is mouse button up
#'
#' Check if a mouse button is NOT being pressed.
#'
#' @param button An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsMouseButtonUp(int button);`
#'
#' @export
is_mouse_button_up <- function(button) {
    .Call(`_raylibr_is_mouse_button_up`, button)
}

#' Get mouse x
#'
#' Get mouse position X.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMouseX(void);`
#'
#' @export
get_mouse_x <- function() {
    .Call(`_raylibr_get_mouse_x`)
}

#' Get mouse y
#'
#' Get mouse position Y.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetMouseY(void);`
#'
#' @export
get_mouse_y <- function() {
    .Call(`_raylibr_get_mouse_y`)
}

#' Get mouse position
#'
#' Get mouse position XY.
#'
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetMousePosition(void);`
#'
#' @export
get_mouse_position <- function() {
    .Call(`_raylibr_get_mouse_position`)
}

#' Get mouse delta
#'
#' Get mouse delta between frames.
#'
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 GetMouseDelta(void);`
#'
#' @export
get_mouse_delta <- function() {
    .Call(`_raylibr_get_mouse_delta`)
}

#' Set mouse position
#'
#' Set mouse position XY.
#'
#' @param x An integer.
#' @param y An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMousePosition(int x, int y);`
#'
#' @export
set_mouse_position <- function(x, y) {
    invisible(.Call(`_raylibr_set_mouse_position`, x, y))
}

#' Set mouse offset
#'
#' Set mouse offset.
#'
#' @param offset_x An integer.
#' @param offset_y An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMouseOffset(int offsetX, int offsetY);`
#'
#' @export
set_mouse_offset <- function(offset_x, offset_y) {
    invisible(.Call(`_raylibr_set_mouse_offset`, offset_x, offset_y))
}

#' Set mouse scale
#'
#' Set mouse scaling.
#'
#' @param scale_x A number.
#' @param scale_y A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMouseScale(float scaleX, float scaleY);`
#'
#' @export
set_mouse_scale <- function(scale_x, scale_y) {
    invisible(.Call(`_raylibr_set_mouse_scale`, scale_x, scale_y))
}

#' Get mouse wheel move
#'
#' Get mouse wheel movement Y.
#'
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float GetMouseWheelMove(void);`
#'
#' @export
get_mouse_wheel_move <- function() {
    .Call(`_raylibr_get_mouse_wheel_move`)
}

#' Set mouse cursor
#'
#' Set mouse cursor.
#'
#' @param cursor An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMouseCursor(int cursor);`
#'
#' @export
set_mouse_cursor <- function(cursor) {
    invisible(.Call(`_raylibr_set_mouse_cursor`, cursor))
}

#' Set camera pan control
#'
#' Set camera pan key to combine with mouse movement (free camera).
#'
#' @param key_pan An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetCameraPanControl(int keyPan);`
#'
#' @export
set_camera_pan_control <- function(key_pan) {
    invisible(.Call(`_raylibr_set_camera_pan_control`, key_pan))
}

#' Set camera alt control
#'
#' Set camera alt key to combine with mouse movement (free camera).
#'
#' @param key_alt An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetCameraAltControl(int keyAlt);`
#'
#' @export
set_camera_alt_control <- function(key_alt) {
    invisible(.Call(`_raylibr_set_camera_alt_control`, key_alt))
}

#' Set camera smooth zoom control
#'
#' Set camera smooth zoom key to combine with mouse (free camera).
#'
#' @param key_smooth_zoom An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetCameraSmoothZoomControl(int keySmoothZoom);`
#'
#' @export
set_camera_smooth_zoom_control <- function(key_smooth_zoom) {
    invisible(.Call(`_raylibr_set_camera_smooth_zoom_control`, key_smooth_zoom))
}

#' Set camera move controls
#'
#' Set camera move controls (1st person and 3rd person cameras).
#'
#' @param key_front An integer.
#' @param key_back An integer.
#' @param key_right An integer.
#' @param key_left An integer.
#' @param key_up An integer.
#' @param key_down An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetCameraMoveControls(int keyFront, int keyBack, int keyRight, int keyLeft, int keyUp, int keyDown);`
#'
#' @export
set_camera_move_controls <- function(key_front, key_back, key_right, key_left, key_up, key_down) {
    invisible(.Call(`_raylibr_set_camera_move_controls`, key_front, key_back, key_right, key_left, key_up, key_down))
}

#' Set shapes texture
#'
#' Set texture and rectangle to be used on shapes drawing.
#'
#' @param texture A texture.
#' @param source A rectangle.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetShapesTexture(Texture2D texture, Rectangle source);`
#'
#' @export
set_shapes_texture <- function(texture, source) {
    invisible(.Call(`_raylibr_set_shapes_texture`, texture, source))
}

#' Draw pixel
#'
#' Draw a pixel.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawPixel(int posX, int posY, Color color);`
#'
#' @export
draw_pixel <- function(pos_x, pos_y, color) {
    invisible(.Call(`_raylibr_draw_pixel`, pos_x, pos_y, color))
}

#' Draw pixel v
#'
#' Draw a pixel (Vector version).
#'
#' @param position A numeric vector of length 2.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawPixelV(Vector2 position, Color color);`
#'
#' @export
draw_pixel_v <- function(position, color) {
    invisible(.Call(`_raylibr_draw_pixel_v`, position, color))
}

#' Draw line
#'
#' Draw a line.
#'
#' @param start_pos_x An integer.
#' @param start_pos_y An integer.
#' @param end_pos_x An integer.
#' @param end_pos_y An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color);`
#'
#' @export
draw_line <- function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, color) {
    invisible(.Call(`_raylibr_draw_line`, start_pos_x, start_pos_y, end_pos_x, end_pos_y, color))
}

#' Draw line v
#'
#' Draw a line (Vector version).
#'
#' @param start_pos A numeric vector of length 2.
#' @param end_pos A numeric vector of length 2.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLineV(Vector2 startPos, Vector2 endPos, Color color);`
#'
#' @export
draw_line_v <- function(start_pos, end_pos, color) {
    invisible(.Call(`_raylibr_draw_line_v`, start_pos, end_pos, color))
}

#' Draw line ex
#'
#' Draw a line defining thickness.
#'
#' @param start_pos A numeric vector of length 2.
#' @param end_pos A numeric vector of length 2.
#' @param thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color);`
#'
#' @export
draw_line_ex <- function(start_pos, end_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_ex`, start_pos, end_pos, thick, color))
}

#' Draw line bezier
#'
#' Draw a line using cubic-bezier curves in-out.
#'
#' @param start_pos A numeric vector of length 2.
#' @param end_pos A numeric vector of length 2.
#' @param thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color);`
#'
#' @export
draw_line_bezier <- function(start_pos, end_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_bezier`, start_pos, end_pos, thick, color))
}

#' Draw line bezier quad
#'
#' Draw line using quadratic bezier curves with a control point.
#'
#' @param start_pos A numeric vector of length 2.
#' @param end_pos A numeric vector of length 2.
#' @param control_pos A numeric vector of length 2.
#' @param thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLineBezierQuad(Vector2 startPos, Vector2 endPos, Vector2 controlPos, float thick, Color color);`
#'
#' @export
draw_line_bezier_quad <- function(start_pos, end_pos, control_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_bezier_quad`, start_pos, end_pos, control_pos, thick, color))
}

#' Draw line bezier cubic
#'
#' Draw line using cubic bezier curves with 2 control points.
#'
#' @param start_pos A numeric vector of length 2.
#' @param end_pos A numeric vector of length 2.
#' @param start_control_pos A numeric vector of length 2.
#' @param end_control_pos A numeric vector of length 2.
#' @param thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawLineBezierCubic(Vector2 startPos, Vector2 endPos, Vector2 startControlPos, Vector2 endControlPos, float thick, Color color);`
#'
#' @export
draw_line_bezier_cubic <- function(start_pos, end_pos, start_control_pos, end_control_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_bezier_cubic`, start_pos, end_pos, start_control_pos, end_control_pos, thick, color))
}

#' Draw circle
#'
#' Draw a color-filled circle.
#'
#' @param center_x An integer.
#' @param center_y An integer.
#' @param radius A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircle(int centerX, int centerY, float radius, Color color);`
#'
#' @export
draw_circle <- function(center_x, center_y, radius, color) {
    invisible(.Call(`_raylibr_draw_circle`, center_x, center_y, radius, color))
}

#' Draw circle sector
#'
#' Draw a piece of a circle.
#'
#' @param center A numeric vector of length 2.
#' @param radius A number.
#' @param start_angle A number.
#' @param end_angle A number.
#' @param segments An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircleSector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);`
#'
#' @export
draw_circle_sector <- function(center, radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_circle_sector`, center, radius, start_angle, end_angle, segments, color))
}

#' Draw circle sector lines
#'
#' Draw circle sector outline.
#'
#' @param center A numeric vector of length 2.
#' @param radius A number.
#' @param start_angle A number.
#' @param end_angle A number.
#' @param segments An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircleSectorLines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color);`
#'
#' @export
draw_circle_sector_lines <- function(center, radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_circle_sector_lines`, center, radius, start_angle, end_angle, segments, color))
}

#' Draw circle gradient
#'
#' Draw a gradient-filled circle.
#'
#' @param center_x An integer.
#' @param center_y An integer.
#' @param radius A number.
#' @param color_1 A color.
#' @param color_2 A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircleGradient(int centerX, int centerY, float radius, Color color1, Color color2);`
#'
#' @export
draw_circle_gradient <- function(center_x, center_y, radius, color_1, color_2) {
    invisible(.Call(`_raylibr_draw_circle_gradient`, center_x, center_y, radius, color_1, color_2))
}

#' Draw circle v
#'
#' Draw a color-filled circle (Vector version).
#'
#' @param center A numeric vector of length 2.
#' @param radius A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircleV(Vector2 center, float radius, Color color);`
#'
#' @export
draw_circle_v <- function(center, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_v`, center, radius, color))
}

#' Draw circle lines
#'
#' Draw circle outline.
#'
#' @param center_x An integer.
#' @param center_y An integer.
#' @param radius A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCircleLines(int centerX, int centerY, float radius, Color color);`
#'
#' @export
draw_circle_lines <- function(center_x, center_y, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_lines`, center_x, center_y, radius, color))
}

#' Draw ellipse
#'
#' Draw ellipse.
#'
#' @param center_x An integer.
#' @param center_y An integer.
#' @param radius_h A number.
#' @param radius_v A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color);`
#'
#' @export
draw_ellipse <- function(center_x, center_y, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse`, center_x, center_y, radius_h, radius_v, color))
}

#' Draw ellipse lines
#'
#' Draw ellipse outline.
#'
#' @param center_x An integer.
#' @param center_y An integer.
#' @param radius_h A number.
#' @param radius_v A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color);`
#'
#' @export
draw_ellipse_lines <- function(center_x, center_y, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse_lines`, center_x, center_y, radius_h, radius_v, color))
}

#' Draw ring
#'
#' Draw ring.
#'
#' @param center A numeric vector of length 2.
#' @param inner_radius A number.
#' @param outer_radius A number.
#' @param start_angle A number.
#' @param end_angle A number.
#' @param segments An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRing(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);`
#'
#' @export
draw_ring <- function(center, inner_radius, outer_radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_ring`, center, inner_radius, outer_radius, start_angle, end_angle, segments, color))
}

#' Draw ring lines
#'
#' Draw ring outline.
#'
#' @param center A numeric vector of length 2.
#' @param inner_radius A number.
#' @param outer_radius A number.
#' @param start_angle A number.
#' @param end_angle A number.
#' @param segments An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRingLines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color);`
#'
#' @export
draw_ring_lines <- function(center, inner_radius, outer_radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_ring_lines`, center, inner_radius, outer_radius, start_angle, end_angle, segments, color))
}

#' Draw rectangle
#'
#' Draw a color-filled rectangle.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param width An integer.
#' @param height An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangle(int posX, int posY, int width, int height, Color color);`
#'
#' @export
draw_rectangle <- function(pos_x, pos_y, width, height, color) {
    invisible(.Call(`_raylibr_draw_rectangle`, pos_x, pos_y, width, height, color))
}

#' Draw rectangle v
#'
#' Draw a color-filled rectangle (Vector version).
#'
#' @param position A numeric vector of length 2.
#' @param size A numeric vector of length 2.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleV(Vector2 position, Vector2 size, Color color);`
#'
#' @export
draw_rectangle_v <- function(position, size, color) {
    invisible(.Call(`_raylibr_draw_rectangle_v`, position, size, color))
}

#' Draw rectangle rec
#'
#' Draw a color-filled rectangle.
#'
#' @param rec A rectangle.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleRec(Rectangle rec, Color color);`
#'
#' @export
draw_rectangle_rec <- function(rec, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rec`, rec, color))
}

#' Draw rectangle pro
#'
#' Draw a color-filled rectangle with pro parameters.
#'
#' @param rec A rectangle.
#' @param origin A numeric vector of length 2.
#' @param rotation A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color);`
#'
#' @export
draw_rectangle_pro <- function(rec, origin, rotation, color) {
    invisible(.Call(`_raylibr_draw_rectangle_pro`, rec, origin, rotation, color))
}

#' Draw rectangle gradient v
#'
#' Draw a vertical-gradient-filled rectangle.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param width An integer.
#' @param height An integer.
#' @param color_1 A color.
#' @param color_2 A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleGradientV(int posX, int posY, int width, int height, Color color1, Color color2);`
#'
#' @export
draw_rectangle_gradient_v <- function(pos_x, pos_y, width, height, color_1, color_2) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_v`, pos_x, pos_y, width, height, color_1, color_2))
}

#' Draw rectangle gradient h
#'
#' Draw a horizontal-gradient-filled rectangle.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param width An integer.
#' @param height An integer.
#' @param color_1 A color.
#' @param color_2 A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleGradientH(int posX, int posY, int width, int height, Color color1, Color color2);`
#'
#' @export
draw_rectangle_gradient_h <- function(pos_x, pos_y, width, height, color_1, color_2) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_h`, pos_x, pos_y, width, height, color_1, color_2))
}

#' Draw rectangle gradient ex
#'
#' Draw a gradient-filled rectangle with custom vertex colors.
#'
#' @param rec A rectangle.
#' @param col_1 A color.
#' @param col_2 A color.
#' @param col_3 A color.
#' @param col_4 A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleGradientEx(Rectangle rec, Color col1, Color col2, Color col3, Color col4);`
#'
#' @export
draw_rectangle_gradient_ex <- function(rec, col_1, col_2, col_3, col_4) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_ex`, rec, col_1, col_2, col_3, col_4))
}

#' Draw rectangle lines
#'
#' Draw rectangle outline.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param width An integer.
#' @param height An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleLines(int posX, int posY, int width, int height, Color color);`
#'
#' @export
draw_rectangle_lines <- function(pos_x, pos_y, width, height, color) {
    invisible(.Call(`_raylibr_draw_rectangle_lines`, pos_x, pos_y, width, height, color))
}

#' Draw rectangle lines ex
#'
#' Draw rectangle outline with extended parameters.
#'
#' @param rec A rectangle.
#' @param line_thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleLinesEx(Rectangle rec, float lineThick, Color color);`
#'
#' @export
draw_rectangle_lines_ex <- function(rec, line_thick, color) {
    invisible(.Call(`_raylibr_draw_rectangle_lines_ex`, rec, line_thick, color))
}

#' Draw rectangle rounded
#'
#' Draw rectangle with rounded edges.
#'
#' @param rec A rectangle.
#' @param roundness A number.
#' @param segments An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color);`
#'
#' @export
draw_rectangle_rounded <- function(rec, roundness, segments, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rounded`, rec, roundness, segments, color))
}

#' Draw rectangle rounded lines
#'
#' Draw rectangle with rounded edges outline.
#'
#' @param rec A rectangle.
#' @param roundness A number.
#' @param segments An integer.
#' @param line_thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, float lineThick, Color color);`
#'
#' @export
draw_rectangle_rounded_lines <- function(rec, roundness, segments, line_thick, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rounded_lines`, rec, roundness, segments, line_thick, color))
}

#' Draw triangle
#'
#' Draw a color-filled triangle (vertex in counter-clockwise order!).
#'
#' @param v_1 A numeric vector of length 2.
#' @param v_2 A numeric vector of length 2.
#' @param v_3 A numeric vector of length 2.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);`
#'
#' @export
draw_triangle <- function(v_1, v_2, v_3, color) {
    invisible(.Call(`_raylibr_draw_triangle`, v_1, v_2, v_3, color))
}

#' Draw triangle lines
#'
#' Draw triangle outline (vertex in counter-clockwise order!).
#'
#' @param v_1 A numeric vector of length 2.
#' @param v_2 A numeric vector of length 2.
#' @param v_3 A numeric vector of length 2.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);`
#'
#' @export
draw_triangle_lines <- function(v_1, v_2, v_3, color) {
    invisible(.Call(`_raylibr_draw_triangle_lines`, v_1, v_2, v_3, color))
}

#' Draw poly
#'
#' Draw a regular polygon (Vector version).
#'
#' @param center A numeric vector of length 2.
#' @param sides An integer.
#' @param radius A number.
#' @param rotation A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);`
#'
#' @export
draw_poly <- function(center, sides, radius, rotation, color) {
    invisible(.Call(`_raylibr_draw_poly`, center, sides, radius, rotation, color))
}

#' Draw poly lines
#'
#' Draw a polygon outline of n sides.
#'
#' @param center A numeric vector of length 2.
#' @param sides An integer.
#' @param radius A number.
#' @param rotation A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color);`
#'
#' @export
draw_poly_lines <- function(center, sides, radius, rotation, color) {
    invisible(.Call(`_raylibr_draw_poly_lines`, center, sides, radius, rotation, color))
}

#' Draw poly lines ex
#'
#' Draw a polygon outline of n sides with extended parameters.
#'
#' @param center A numeric vector of length 2.
#' @param sides An integer.
#' @param radius A number.
#' @param rotation A number.
#' @param line_thick A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawPolyLinesEx(Vector2 center, int sides, float radius, float rotation, float lineThick, Color color);`
#'
#' @export
draw_poly_lines_ex <- function(center, sides, radius, rotation, line_thick, color) {
    invisible(.Call(`_raylibr_draw_poly_lines_ex`, center, sides, radius, rotation, line_thick, color))
}

#' Check collision recs
#'
#' Check collision between two rectangles.
#'
#' @param rec_1 A rectangle.
#' @param rec_2 A rectangle.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionRecs(Rectangle rec1, Rectangle rec2);`
#'
#' @export
check_collision_recs <- function(rec_1, rec_2) {
    .Call(`_raylibr_check_collision_recs`, rec_1, rec_2)
}

#' Check collision circles
#'
#' Check collision between two circles.
#'
#' @param center_1 A numeric vector of length 2.
#' @param radius_1 A number.
#' @param center_2 A numeric vector of length 2.
#' @param radius_2 A number.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionCircles(Vector2 center1, float radius1, Vector2 center2, float radius2);`
#'
#' @export
check_collision_circles <- function(center_1, radius_1, center_2, radius_2) {
    .Call(`_raylibr_check_collision_circles`, center_1, radius_1, center_2, radius_2)
}

#' Check collision circle rec
#'
#' Check collision between circle and rectangle.
#'
#' @param center A numeric vector of length 2.
#' @param radius A number.
#' @param rec A rectangle.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionCircleRec(Vector2 center, float radius, Rectangle rec);`
#'
#' @export
check_collision_circle_rec <- function(center, radius, rec) {
    .Call(`_raylibr_check_collision_circle_rec`, center, radius, rec)
}

#' Check collision point rec
#'
#' Check if point is inside rectangle.
#'
#' @param point A numeric vector of length 2.
#' @param rec A rectangle.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionPointRec(Vector2 point, Rectangle rec);`
#'
#' @export
check_collision_point_rec <- function(point, rec) {
    .Call(`_raylibr_check_collision_point_rec`, point, rec)
}

#' Check collision point circle
#'
#' Check if point is inside circle.
#'
#' @param point A numeric vector of length 2.
#' @param center A numeric vector of length 2.
#' @param radius A number.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionPointCircle(Vector2 point, Vector2 center, float radius);`
#'
#' @export
check_collision_point_circle <- function(point, center, radius) {
    .Call(`_raylibr_check_collision_point_circle`, point, center, radius)
}

#' Check collision point triangle
#'
#' Check if point is inside a triangle.
#'
#' @param point A numeric vector of length 2.
#' @param p_1 A numeric vector of length 2.
#' @param p_2 A numeric vector of length 2.
#' @param p_3 A numeric vector of length 2.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3);`
#'
#' @export
check_collision_point_triangle <- function(point, p_1, p_2, p_3) {
    .Call(`_raylibr_check_collision_point_triangle`, point, p_1, p_2, p_3)
}

#' Check collision point line
#'
#' Check if point belongs to line created between two points [p1] and [p2] with defined margin in pixels [threshold].
#'
#' @param point A numeric vector of length 2.
#' @param p_1 A numeric vector of length 2.
#' @param p_2 A numeric vector of length 2.
#' @param threshold An integer.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool CheckCollisionPointLine(Vector2 point, Vector2 p1, Vector2 p2, int threshold);`
#'
#' @export
check_collision_point_line <- function(point, p_1, p_2, threshold) {
    .Call(`_raylibr_check_collision_point_line`, point, p_1, p_2, threshold)
}

#' Get collision rec
#'
#' Get collision rectangle for two rectangles collision.
#'
#' @param rec_1 A rectangle.
#' @param rec_2 A rectangle.
#' @return A rectangle
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Rectangle GetCollisionRec(Rectangle rec1, Rectangle rec2);`
#'
#' @export
get_collision_rec <- function(rec_1, rec_2) {
    .Call(`_raylibr_get_collision_rec`, rec_1, rec_2)
}

#' Load image
#'
#' Load image from file into CPU memory (RAM).
#'
#' @param file_name A string.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image LoadImage(const char *fileName);`
#'
#' @export
load_image <- function(file_name) {
    .Call(`_raylibr_load_image`, file_name)
}

#' Load image raw
#'
#' Load image from RAW file data.
#'
#' @param file_name A string.
#' @param width An integer.
#' @param height An integer.
#' @param format An integer.
#' @param header_size An integer.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize);`
#'
#' @export
load_image_raw <- function(file_name, width, height, format, header_size) {
    .Call(`_raylibr_load_image_raw`, file_name, width, height, format, header_size)
}

#' Load image from texture
#'
#' Load image from GPU texture data.
#'
#' @param texture A texture.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image LoadImageFromTexture(Texture2D texture);`
#'
#' @export
load_image_from_texture <- function(texture) {
    .Call(`_raylibr_load_image_from_texture`, texture)
}

#' Load image from screen
#'
#' Load image from screen buffer and (screenshot).
#'
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image LoadImageFromScreen(void);`
#'
#' @export
load_image_from_screen <- function() {
    .Call(`_raylibr_load_image_from_screen`)
}

#' Unload image
#'
#' Unload image from CPU memory (RAM).
#'
#' @param image A image.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UnloadImage(Image image);`
#'
#' @export
unload_image <- function(image) {
    invisible(.Call(`_raylibr_unload_image`, image))
}

#' Export image
#'
#' Export image data to file, returns true on success.
#'
#' @param image A image.
#' @param file_name A string.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool ExportImage(Image image, const char *fileName);`
#'
#' @export
export_image <- function(image, file_name) {
    .Call(`_raylibr_export_image`, image, file_name)
}

#' Export image as code
#'
#' Export image as code file defining an array of bytes, returns true on success.
#'
#' @param image A image.
#' @param file_name A string.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool ExportImageAsCode(Image image, const char *fileName);`
#'
#' @export
export_image_as_code <- function(image, file_name) {
    .Call(`_raylibr_export_image_as_code`, image, file_name)
}

#' Gen image color
#'
#' Generate image: plain color.
#'
#' @param width An integer.
#' @param height An integer.
#' @param color A color.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageColor(int width, int height, Color color);`
#'
#' @export
gen_image_color <- function(width, height, color) {
    .Call(`_raylibr_gen_image_color`, width, height, color)
}

#' Gen image gradient v
#'
#' Generate image: vertical gradient.
#'
#' @param width An integer.
#' @param height An integer.
#' @param top A color.
#' @param bottom A color.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageGradientV(int width, int height, Color top, Color bottom);`
#'
#' @export
gen_image_gradient_v <- function(width, height, top, bottom) {
    .Call(`_raylibr_gen_image_gradient_v`, width, height, top, bottom)
}

#' Gen image gradient h
#'
#' Generate image: horizontal gradient.
#'
#' @param width An integer.
#' @param height An integer.
#' @param left A color.
#' @param right A color.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageGradientH(int width, int height, Color left, Color right);`
#'
#' @export
gen_image_gradient_h <- function(width, height, left, right) {
    .Call(`_raylibr_gen_image_gradient_h`, width, height, left, right)
}

#' Gen image gradient radial
#'
#' Generate image: radial gradient.
#'
#' @param width An integer.
#' @param height An integer.
#' @param density A number.
#' @param inner A color.
#' @param outer A color.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageGradientRadial(int width, int height, float density, Color inner, Color outer);`
#'
#' @export
gen_image_gradient_radial <- function(width, height, density, inner, outer) {
    .Call(`_raylibr_gen_image_gradient_radial`, width, height, density, inner, outer)
}

#' Gen image checked
#'
#' Generate image: checked.
#'
#' @param width An integer.
#' @param height An integer.
#' @param checks_x An integer.
#' @param checks_y An integer.
#' @param col_1 A color.
#' @param col_2 A color.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2);`
#'
#' @export
gen_image_checked <- function(width, height, checks_x, checks_y, col_1, col_2) {
    .Call(`_raylibr_gen_image_checked`, width, height, checks_x, checks_y, col_1, col_2)
}

#' Gen image white noise
#'
#' Generate image: white noise.
#'
#' @param width An integer.
#' @param height An integer.
#' @param factor A number.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageWhiteNoise(int width, int height, float factor);`
#'
#' @export
gen_image_white_noise <- function(width, height, factor) {
    .Call(`_raylibr_gen_image_white_noise`, width, height, factor)
}

#' Gen image cellular
#'
#' Generate image: cellular algorithm, bigger tileSize means bigger cells.
#'
#' @param width An integer.
#' @param height An integer.
#' @param tile_size An integer.
#' @return A image
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Image GenImageCellular(int width, int height, int tileSize);`
#'
#' @export
gen_image_cellular <- function(width, height, tile_size) {
    .Call(`_raylibr_gen_image_cellular`, width, height, tile_size)
}

#' Get image alpha border
#'
#' Get image alpha border rectangle.
#'
#' @param image A image.
#' @param threshold A number.
#' @return A rectangle
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Rectangle GetImageAlphaBorder(Image image, float threshold);`
#'
#' @export
get_image_alpha_border <- function(image, threshold) {
    .Call(`_raylibr_get_image_alpha_border`, image, threshold)
}

#' Load texture
#'
#' Load texture from file into GPU memory (VRAM).
#'
#' @param file_name A string.
#' @return A texture
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Texture2D LoadTexture(const char *fileName);`
#'
#' @export
load_texture <- function(file_name) {
    .Call(`_raylibr_load_texture`, file_name)
}

#' Load texture from image
#'
#' Load texture from image data.
#'
#' @param image A image.
#' @return A texture
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Texture2D LoadTextureFromImage(Image image);`
#'
#' @export
load_texture_from_image <- function(image) {
    .Call(`_raylibr_load_texture_from_image`, image)
}

#' Draw texture
#'
#' Draw a Texture2D.
#'
#' @param texture A texture.
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param tint A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawTexture(Texture2D texture, int posX, int posY, Color tint);`
#'
#' @export
draw_texture <- function(texture, pos_x, pos_y, tint) {
    invisible(.Call(`_raylibr_draw_texture`, texture, pos_x, pos_y, tint))
}

#' Fade
#'
#' Get color with alpha applied, alpha goes from 0.0f to 1.0f.
#'
#' @param color A color.
#' @param alpha A number.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color Fade(Color color, float alpha);`
#'
#' @export
fade <- function(color, alpha) {
    .Call(`_raylibr_fade`, color, alpha)
}

#' Color to int
#'
#' Get hexadecimal value for a Color.
#'
#' @param color A color.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int ColorToInt(Color color);`
#'
#' @export
color_to_int <- function(color) {
    .Call(`_raylibr_color_to_int`, color)
}

#' Color normalize
#'
#' Get Color normalized as float [0..1].
#'
#' @param color A color.
#' @return A numeric vector of length 4
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector4 ColorNormalize(Color color);`
#'
#' @export
color_normalize <- function(color) {
    .Call(`_raylibr_color_normalize`, color)
}

#' Color from normalized
#'
#' Get Color from normalized values [0..1].
#'
#' @param normalized A numeric vector of length 4.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color ColorFromNormalized(Vector4 normalized);`
#'
#' @export
color_from_normalized <- function(normalized) {
    .Call(`_raylibr_color_from_normalized`, normalized)
}

#' Color to hsv
#'
#' Get HSV values for a Color, hue [0..360], saturation/value [0..1].
#'
#' @param color A color.
#' @return A numeric vector of length 3
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector3 ColorToHSV(Color color);`
#'
#' @export
color_to_hsv <- function(color) {
    .Call(`_raylibr_color_to_hsv`, color)
}

#' Color from hsv
#'
#' Get a Color from HSV values, hue [0..360], saturation/value [0..1].
#'
#' @param hue A number.
#' @param saturation A number.
#' @param value A number.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color ColorFromHSV(float hue, float saturation, float value);`
#'
#' @export
color_from_hsv <- function(hue, saturation, value) {
    .Call(`_raylibr_color_from_hsv`, hue, saturation, value)
}

#' Color alpha
#'
#' Get color with alpha applied, alpha goes from 0.0f to 1.0f.
#'
#' @param color A color.
#' @param alpha A number.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color ColorAlpha(Color color, float alpha);`
#'
#' @export
color_alpha <- function(color, alpha) {
    .Call(`_raylibr_color_alpha`, color, alpha)
}

#' Color alpha blend
#'
#' Get src alpha-blended into dst color with tint.
#'
#' @param dst A color.
#' @param src A color.
#' @param tint A color.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color ColorAlphaBlend(Color dst, Color src, Color tint);`
#'
#' @export
color_alpha_blend <- function(dst, src, tint) {
    .Call(`_raylibr_color_alpha_blend`, dst, src, tint)
}

#' Get color
#'
#' Get Color structure from hexadecimal value.
#'
#' @param hex_value A non-negative integer.
#' @return A color
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Color GetColor(unsigned int hexValue);`
#'
#' @export
get_color <- function(hex_value) {
    .Call(`_raylibr_get_color`, hex_value)
}

#' Get font default
#'
#' Get the default Font.
#'
#' @return A font
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Font GetFontDefault(void);`
#'
#' @export
get_font_default <- function() {
    .Call(`_raylibr_get_font_default`)
}

#' Load font
#'
#' Load font from file into GPU memory (VRAM).
#'
#' @param file_name A string.
#' @return A font
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Font LoadFont(const char *fileName);`
#'
#' @export
load_font <- function(file_name) {
    .Call(`_raylibr_load_font`, file_name)
}

#' Unload font
#'
#' Unload Font from GPU memory (VRAM).
#'
#' @param font A font.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UnloadFont(Font font);`
#'
#' @export
unload_font <- function(font) {
    invisible(.Call(`_raylibr_unload_font`, font))
}

#' Draw fps
#'
#' Draw current FPS.
#'
#' @param pos_x An integer.
#' @param pos_y An integer.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawFPS(int posX, int posY);`
#'
#' @export
draw_fps <- function(pos_x, pos_y) {
    invisible(.Call(`_raylibr_draw_fps`, pos_x, pos_y))
}

#' Draw text
#'
#' Draw text (using default font).
#'
#' @param text A string.
#' @param pos_x An integer.
#' @param pos_y An integer.
#' @param font_size An integer.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawText(const char *text, int posX, int posY, int fontSize, Color color);`
#'
#' @export
draw_text <- function(text, pos_x, pos_y, font_size, color) {
    invisible(.Call(`_raylibr_draw_text`, text, pos_x, pos_y, font_size, color))
}

#' Draw text ex
#'
#' Draw text using font and additional parameters.
#'
#' @param font A font.
#' @param text A string.
#' @param position A numeric vector of length 2.
#' @param font_size A number.
#' @param spacing A number.
#' @param tint A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawTextEx(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);`
#'
#' @export
draw_text_ex <- function(font, text, position, font_size, spacing, tint) {
    invisible(.Call(`_raylibr_draw_text_ex`, font, text, position, font_size, spacing, tint))
}

#' Measure text
#'
#' Measure string width for default font.
#'
#' @param text A string.
#' @param font_size An integer.
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int MeasureText(const char *text, int fontSize);`
#'
#' @export
measure_text <- function(text, font_size) {
    .Call(`_raylibr_measure_text`, text, font_size)
}

#' Measure text ex
#'
#' Measure string size for Font.
#'
#' @param font A font.
#' @param text A string.
#' @param font_size A number.
#' @param spacing A number.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 MeasureTextEx(Font font, const char *text, float fontSize, float spacing);`
#'
#' @export
measure_text_ex <- function(font, text, font_size, spacing) {
    .Call(`_raylibr_measure_text_ex`, font, text, font_size, spacing)
}

#' Draw cube
#'
#' Draw cube.
#'
#' @param position A numeric vector of length 3.
#' @param width A number.
#' @param height A number.
#' @param length A number.
#' @param color A color.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawCube(Vector3 position, float width, float height, float length, Color color);`
#'
#' @export
draw_cube <- function(position, width, height, length, color) {
    invisible(.Call(`_raylibr_draw_cube`, position, width, height, length, color))
}

#' Draw grid
#'
#' Draw a grid (centered at (0, 0, 0)).
#'
#' @param slices An integer.
#' @param spacing A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void DrawGrid(int slices, float spacing);`
#'
#' @export
draw_grid <- function(slices, spacing) {
    invisible(.Call(`_raylibr_draw_grid`, slices, spacing))
}

#' Init audio device
#'
#' Initialize audio device and context.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void InitAudioDevice(void);`
#'
#' @export
init_audio_device <- function() {
    invisible(.Call(`_raylibr_init_audio_device`))
}

#' Close audio device
#'
#' Close the audio device and context.
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void CloseAudioDevice(void);`
#'
#' @export
close_audio_device <- function() {
    invisible(.Call(`_raylibr_close_audio_device`))
}

#' Is audio device ready
#'
#' Check if audio device has been initialized successfully.
#'
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsAudioDeviceReady(void);`
#'
#' @export
is_audio_device_ready <- function() {
    .Call(`_raylibr_is_audio_device_ready`)
}

#' Set master volume
#'
#' Set master volume (listener).
#'
#' @param volume A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMasterVolume(float volume);`
#'
#' @export
set_master_volume <- function(volume) {
    invisible(.Call(`_raylibr_set_master_volume`, volume))
}

#' Load wave
#'
#' Load wave data from file.
#'
#' @param file_name A string.
#' @return A wave
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Wave LoadWave(const char *fileName);`
#'
#' @export
load_wave <- function(file_name) {
    .Call(`_raylibr_load_wave`, file_name)
}

#' Load sound
#'
#' Load sound from file.
#'
#' @param file_name A string.
#' @return A sound
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Sound LoadSound(const char *fileName);`
#'
#' @export
load_sound <- function(file_name) {
    .Call(`_raylibr_load_sound`, file_name)
}

#' Load sound from wave
#'
#' Load sound from wave data.
#'
#' @param wave A wave.
#' @return A sound
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Sound LoadSoundFromWave(Wave wave);`
#'
#' @export
load_sound_from_wave <- function(wave) {
    .Call(`_raylibr_load_sound_from_wave`, wave)
}

#' Unload wave
#'
#' Unload wave data.
#'
#' @param wave A wave.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UnloadWave(Wave wave);`
#'
#' @export
unload_wave <- function(wave) {
    invisible(.Call(`_raylibr_unload_wave`, wave))
}

#' Unload sound
#'
#' Unload sound.
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UnloadSound(Sound sound);`
#'
#' @export
unload_sound <- function(sound) {
    invisible(.Call(`_raylibr_unload_sound`, sound))
}

#' Play sound
#'
#' Play a sound.
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void PlaySound(Sound sound);`
#'
#' @export
play_sound <- function(sound) {
    invisible(.Call(`_raylibr_play_sound`, sound))
}

#' Stop sound
#'
#' Stop playing a sound.
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void StopSound(Sound sound);`
#'
#' @export
stop_sound <- function(sound) {
    invisible(.Call(`_raylibr_stop_sound`, sound))
}

#' Pause sound
#'
#' Pause a sound.
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void PauseSound(Sound sound);`
#'
#' @export
pause_sound <- function(sound) {
    invisible(.Call(`_raylibr_pause_sound`, sound))
}

#' Resume sound
#'
#' Resume a paused sound.
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ResumeSound(Sound sound);`
#'
#' @export
resume_sound <- function(sound) {
    invisible(.Call(`_raylibr_resume_sound`, sound))
}

#' Play sound multi
#'
#' Play a sound (using multichannel buffer pool).
#'
#' @param sound A sound.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void PlaySoundMulti(Sound sound);`
#'
#' @export
play_sound_multi <- function(sound) {
    invisible(.Call(`_raylibr_play_sound_multi`, sound))
}

#' Stop sound multi
#'
#' Stop any sound playing (using multichannel buffer pool).
#'
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void StopSoundMulti(void);`
#'
#' @export
stop_sound_multi <- function() {
    invisible(.Call(`_raylibr_stop_sound_multi`))
}

#' Get sounds playing
#'
#' Get number of sounds playing in the multichannel.
#'
#' @return An integer
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `int GetSoundsPlaying(void);`
#'
#' @export
get_sounds_playing <- function() {
    .Call(`_raylibr_get_sounds_playing`)
}

#' Is sound playing
#'
#' Check if a sound is currently playing.
#'
#' @param sound A sound.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsSoundPlaying(Sound sound);`
#'
#' @export
is_sound_playing <- function(sound) {
    .Call(`_raylibr_is_sound_playing`, sound)
}

#' Set sound volume
#'
#' Set volume for a sound (1.0 is max level).
#'
#' @param sound A sound.
#' @param volume A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetSoundVolume(Sound sound, float volume);`
#'
#' @export
set_sound_volume <- function(sound, volume) {
    invisible(.Call(`_raylibr_set_sound_volume`, sound, volume))
}

#' Set sound pitch
#'
#' Set pitch for a sound (1.0 is base level).
#'
#' @param sound A sound.
#' @param pitch A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetSoundPitch(Sound sound, float pitch);`
#'
#' @export
set_sound_pitch <- function(sound, pitch) {
    invisible(.Call(`_raylibr_set_sound_pitch`, sound, pitch))
}

#' Load music stream
#'
#' Load music stream from file.
#'
#' @param file_name A string.
#' @return A music
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Music LoadMusicStream(const char *fileName);`
#'
#' @export
load_music_stream <- function(file_name) {
    .Call(`_raylibr_load_music_stream`, file_name)
}

#' Unload music stream
#'
#' Unload music stream.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UnloadMusicStream(Music music);`
#'
#' @export
unload_music_stream <- function(music) {
    invisible(.Call(`_raylibr_unload_music_stream`, music))
}

#' Play music stream
#'
#' Start music playing.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void PlayMusicStream(Music music);`
#'
#' @export
play_music_stream <- function(music) {
    invisible(.Call(`_raylibr_play_music_stream`, music))
}

#' Is music stream playing
#'
#' Check if music is playing.
#'
#' @param music A music.
#' @return A logical
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `bool IsMusicStreamPlaying(Music music);`
#'
#' @export
is_music_stream_playing <- function(music) {
    .Call(`_raylibr_is_music_stream_playing`, music)
}

#' Update music stream
#'
#' Updates buffers for music streaming.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void UpdateMusicStream(Music music);`
#'
#' @export
update_music_stream <- function(music) {
    invisible(.Call(`_raylibr_update_music_stream`, music))
}

#' Stop music stream
#'
#' Stop music playing.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void StopMusicStream(Music music);`
#'
#' @export
stop_music_stream <- function(music) {
    invisible(.Call(`_raylibr_stop_music_stream`, music))
}

#' Pause music stream
#'
#' Pause music playing.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void PauseMusicStream(Music music);`
#'
#' @export
pause_music_stream <- function(music) {
    invisible(.Call(`_raylibr_pause_music_stream`, music))
}

#' Resume music stream
#'
#' Resume playing paused music.
#'
#' @param music A music.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void ResumeMusicStream(Music music);`
#'
#' @export
resume_music_stream <- function(music) {
    invisible(.Call(`_raylibr_resume_music_stream`, music))
}

#' Seek music stream
#'
#' Seek music to a position (in seconds).
#'
#' @param music A music.
#' @param position A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SeekMusicStream(Music music, float position);`
#'
#' @export
seek_music_stream <- function(music, position) {
    invisible(.Call(`_raylibr_seek_music_stream`, music, position))
}

#' Set music volume
#'
#' Set volume for music (1.0 is max level).
#'
#' @param music A music.
#' @param volume A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMusicVolume(Music music, float volume);`
#'
#' @export
set_music_volume <- function(music, volume) {
    invisible(.Call(`_raylibr_set_music_volume`, music, volume))
}

#' Set music pitch
#'
#' Set pitch for a music (1.0 is base level).
#'
#' @param music A music.
#' @param pitch A number.
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `void SetMusicPitch(Music music, float pitch);`
#'
#' @export
set_music_pitch <- function(music, pitch) {
    invisible(.Call(`_raylibr_set_music_pitch`, music, pitch))
}

#' Get music time length
#'
#' Get music time length (in seconds).
#'
#' @param music A music.
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float GetMusicTimeLength(Music music);`
#'
#' @export
get_music_time_length <- function(music) {
    .Call(`_raylibr_get_music_time_length`, music)
}

#' Get music time played
#'
#' Get current music time played (in seconds).
#'
#' @param music A music.
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float GetMusicTimePlayed(Music music);`
#'
#' @export
get_music_time_played <- function(music) {
    .Call(`_raylibr_get_music_time_played`, music)
}

#' Vector 2 angle
#'
#' .
#'
#' @param v_1 A numeric vector of length 2.
#' @param v_2 A numeric vector of length 2.
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float Vector2Angle(Vector2 v1, Vector2 v2);`
#'
#' @export
vector_2_angle <- function(v_1, v_2) {
    .Call(`_raylibr_vector_2_angle`, v_1, v_2)
}

#' Vector 2 move towards
#'
#' .
#'
#' @param v A numeric vector of length 2.
#' @param target A numeric vector of length 2.
#' @param max_distance A number.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 Vector2MoveTowards(Vector2 v, Vector2 target, float maxDistance);`
#'
#' @export
vector_2_move_towards <- function(v, target, max_distance) {
    .Call(`_raylibr_vector_2_move_towards`, v, target, max_distance)
}

#' Vector 2 distance
#'
#' .
#'
#' @param v_1 A numeric vector of length 2.
#' @param v_2 A numeric vector of length 2.
#' @return A number
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `float Vector2Distance(Vector2 v1, Vector2 v2);`
#'
#' @export
vector_2_distance <- function(v_1, v_2) {
    .Call(`_raylibr_vector_2_distance`, v_1, v_2)
}

#' Vector 2 rotate
#'
#' .
#'
#' @param v A numeric vector of length 2.
#' @param angle A number.
#' @return A numeric vector of length 2
#'
#' @note This function has been auto-generated from the following Raylib function definition:
#'
#' `Vector2 Vector2Rotate(Vector2 v, float angle);`
#'
#' @export
vector_2_rotate <- function(v, angle) {
    .Call(`_raylibr_vector_2_rotate`, v, angle)
}

camera_2d_ <- function(offset, target, rotation, zoom) {
    .Call(`_raylibr_camera_2d_`, offset, target, rotation, zoom)
}

camera_2d_get_offset_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_offset_`, obj)
}

camera_2d_set_offset_ <- function(obj, offset) {
    .Call(`_raylibr_camera_2d_set_offset_`, obj, offset)
}

camera_2d_get_target_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_target_`, obj)
}

camera_2d_set_target_ <- function(obj, target) {
    .Call(`_raylibr_camera_2d_set_target_`, obj, target)
}

camera_2d_get_rotation_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_rotation_`, obj)
}

camera_2d_set_rotation_ <- function(obj, rotation) {
    .Call(`_raylibr_camera_2d_set_rotation_`, obj, rotation)
}

camera_2d_get_zoom_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_zoom_`, obj)
}

camera_2d_set_zoom_ <- function(obj, zoom) {
    .Call(`_raylibr_camera_2d_set_zoom_`, obj, zoom)
}

camera_3d_ <- function(position, target, up, fovy, projection) {
    .Call(`_raylibr_camera_3d_`, position, target, up, fovy, projection)
}

camera_3d_get_position_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_position_`, obj)
}

camera_3d_set_position_ <- function(obj, position) {
    .Call(`_raylibr_camera_3d_set_position_`, obj, position)
}

camera_3d_get_target_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_target_`, obj)
}

camera_3d_set_target_ <- function(obj, target) {
    .Call(`_raylibr_camera_3d_set_target_`, obj, target)
}

camera_3d_get_up_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_up_`, obj)
}

camera_3d_set_up_ <- function(obj, up) {
    .Call(`_raylibr_camera_3d_set_up_`, obj, up)
}

camera_3d_get_fovy_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_fovy_`, obj)
}

camera_3d_set_fovy_ <- function(obj, fovy) {
    .Call(`_raylibr_camera_3d_set_fovy_`, obj, fovy)
}

camera_3d_get_projection_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_projection_`, obj)
}

camera_3d_set_projection_ <- function(obj, projection) {
    .Call(`_raylibr_camera_3d_set_projection_`, obj, projection)
}

#' @export
color <- function(c) {
    .Call(`_raylibr_color`, c)
}

#' Draw Circle
#' @export
draw_circles <- function(x, y, radius, colors) {
    invisible(.Call(`_raylibr_draw_circles`, x, y, radius, colors))
}

#' Load font ex
#'
#' @param file_name A string
#' @param font_size An integer
#' @return A font
#'
#' @export
load_font_ex <- function(file_name, font_size) {
    .Call(`_raylibr_load_font_ex`, file_name, font_size)
}

#' @export
image_draw_pixel <- function(dst, posX, posY, color) {
    invisible(.Call(`_raylibr_image_draw_pixel`, dst, posX, posY, color))
}

glyph_info_ <- function(value, offset_x, offset_y, advance_x, image) {
    .Call(`_raylibr_glyph_info_`, value, offset_x, offset_y, advance_x, image)
}

glyph_info_get_value_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_value_`, obj)
}

glyph_info_set_value_ <- function(obj, value) {
    .Call(`_raylibr_glyph_info_set_value_`, obj, value)
}

glyph_info_get_offset_x_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_offset_x_`, obj)
}

glyph_info_set_offset_x_ <- function(obj, offset_x) {
    .Call(`_raylibr_glyph_info_set_offset_x_`, obj, offset_x)
}

glyph_info_get_offset_y_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_offset_y_`, obj)
}

glyph_info_set_offset_y_ <- function(obj, offset_y) {
    .Call(`_raylibr_glyph_info_set_offset_y_`, obj, offset_y)
}

glyph_info_get_advance_x_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_advance_x_`, obj)
}

glyph_info_set_advance_x_ <- function(obj, advance_x) {
    .Call(`_raylibr_glyph_info_set_advance_x_`, obj, advance_x)
}

glyph_info_get_image_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_image_`, obj)
}

glyph_info_set_image_ <- function(obj, image) {
    .Call(`_raylibr_glyph_info_set_image_`, obj, image)
}

material_map_ <- function(texture, color, value) {
    .Call(`_raylibr_material_map_`, texture, color, value)
}

material_map_get_texture_ <- function(obj) {
    .Call(`_raylibr_material_map_get_texture_`, obj)
}

material_map_set_texture_ <- function(obj, texture) {
    .Call(`_raylibr_material_map_set_texture_`, obj, texture)
}

material_map_get_color_ <- function(obj) {
    .Call(`_raylibr_material_map_get_color_`, obj)
}

material_map_set_color_ <- function(obj, color) {
    .Call(`_raylibr_material_map_set_color_`, obj, color)
}

material_map_get_value_ <- function(obj) {
    .Call(`_raylibr_material_map_get_value_`, obj)
}

material_map_set_value_ <- function(obj, value) {
    .Call(`_raylibr_material_map_set_value_`, obj, value)
}

npatch_info_ <- function(source, left, top, right, bottom, layout) {
    .Call(`_raylibr_npatch_info_`, source, left, top, right, bottom, layout)
}

npatch_info_get_source_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_source_`, obj)
}

npatch_info_set_source_ <- function(obj, source) {
    .Call(`_raylibr_npatch_info_set_source_`, obj, source)
}

npatch_info_get_left_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_left_`, obj)
}

npatch_info_set_left_ <- function(obj, left) {
    .Call(`_raylibr_npatch_info_set_left_`, obj, left)
}

npatch_info_get_top_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_top_`, obj)
}

npatch_info_set_top_ <- function(obj, top) {
    .Call(`_raylibr_npatch_info_set_top_`, obj, top)
}

npatch_info_get_right_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_right_`, obj)
}

npatch_info_set_right_ <- function(obj, right) {
    .Call(`_raylibr_npatch_info_set_right_`, obj, right)
}

npatch_info_get_bottom_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_bottom_`, obj)
}

npatch_info_set_bottom_ <- function(obj, bottom) {
    .Call(`_raylibr_npatch_info_set_bottom_`, obj, bottom)
}

npatch_info_get_layout_ <- function(obj) {
    .Call(`_raylibr_npatch_info_get_layout_`, obj)
}

npatch_info_set_layout_ <- function(obj, layout) {
    .Call(`_raylibr_npatch_info_set_layout_`, obj, layout)
}

rectangle_ <- function(x, y, width, height) {
    .Call(`_raylibr_rectangle_`, x, y, width, height)
}

rectangle_get_x_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_x_`, obj)
}

rectangle_set_x_ <- function(obj, x) {
    .Call(`_raylibr_rectangle_set_x_`, obj, x)
}

rectangle_get_y_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_y_`, obj)
}

rectangle_set_y_ <- function(obj, y) {
    .Call(`_raylibr_rectangle_set_y_`, obj, y)
}

rectangle_get_width_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_width_`, obj)
}

rectangle_set_width_ <- function(obj, width) {
    .Call(`_raylibr_rectangle_set_width_`, obj, width)
}

rectangle_get_height_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_height_`, obj)
}

rectangle_set_height_ <- function(obj, height) {
    .Call(`_raylibr_rectangle_set_height_`, obj, height)
}

render_texture_ <- function(id, texture, depth) {
    .Call(`_raylibr_render_texture_`, id, texture, depth)
}

render_texture_get_id_ <- function(obj) {
    .Call(`_raylibr_render_texture_get_id_`, obj)
}

render_texture_set_id_ <- function(obj, id) {
    .Call(`_raylibr_render_texture_set_id_`, obj, id)
}

render_texture_get_texture_ <- function(obj) {
    .Call(`_raylibr_render_texture_get_texture_`, obj)
}

render_texture_set_texture_ <- function(obj, texture) {
    .Call(`_raylibr_render_texture_set_texture_`, obj, texture)
}

render_texture_get_depth_ <- function(obj) {
    .Call(`_raylibr_render_texture_get_depth_`, obj)
}

render_texture_set_depth_ <- function(obj, depth) {
    .Call(`_raylibr_render_texture_set_depth_`, obj, depth)
}

sound_ <- function(stream, frame_count) {
    .Call(`_raylibr_sound_`, stream, frame_count)
}

sound_get_stream_ <- function(obj) {
    .Call(`_raylibr_sound_get_stream_`, obj)
}

sound_set_stream_ <- function(obj, stream) {
    .Call(`_raylibr_sound_set_stream_`, obj, stream)
}

sound_get_frame_count_ <- function(obj) {
    .Call(`_raylibr_sound_get_frame_count_`, obj)
}

sound_set_frame_count_ <- function(obj, frame_count) {
    .Call(`_raylibr_sound_set_frame_count_`, obj, frame_count)
}

texture_ <- function(id, width, height, mipmaps, format) {
    .Call(`_raylibr_texture_`, id, width, height, mipmaps, format)
}

texture_get_id_ <- function(obj) {
    .Call(`_raylibr_texture_get_id_`, obj)
}

texture_set_id_ <- function(obj, id) {
    .Call(`_raylibr_texture_set_id_`, obj, id)
}

texture_get_width_ <- function(obj) {
    .Call(`_raylibr_texture_get_width_`, obj)
}

texture_set_width_ <- function(obj, width) {
    .Call(`_raylibr_texture_set_width_`, obj, width)
}

texture_get_height_ <- function(obj) {
    .Call(`_raylibr_texture_get_height_`, obj)
}

texture_set_height_ <- function(obj, height) {
    .Call(`_raylibr_texture_set_height_`, obj, height)
}

texture_get_mipmaps_ <- function(obj) {
    .Call(`_raylibr_texture_get_mipmaps_`, obj)
}

texture_set_mipmaps_ <- function(obj, mipmaps) {
    .Call(`_raylibr_texture_set_mipmaps_`, obj, mipmaps)
}

texture_get_format_ <- function(obj) {
    .Call(`_raylibr_texture_get_format_`, obj)
}

texture_set_format_ <- function(obj, format) {
    .Call(`_raylibr_texture_set_format_`, obj, format)
}

