# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_audio_device_ready_ <- function() {
    .Call(`_raylibr_is_audio_device_ready_`)
}

load_wave_ <- function(file_name) {
    .Call(`_raylibr_load_wave_`, file_name)
}

is_wave_valid_ <- function(wave) {
    .Call(`_raylibr_is_wave_valid_`, wave)
}

load_sound_ <- function(file_name) {
    .Call(`_raylibr_load_sound_`, file_name)
}

load_sound_from_wave_ <- function(wave) {
    .Call(`_raylibr_load_sound_from_wave_`, wave)
}

load_sound_alias_ <- function(source) {
    .Call(`_raylibr_load_sound_alias_`, source)
}

is_sound_valid_ <- function(sound) {
    .Call(`_raylibr_is_sound_valid_`, sound)
}

unload_wave_ <- function(wave) {
    invisible(.Call(`_raylibr_unload_wave_`, wave))
}

unload_sound_ <- function(sound) {
    invisible(.Call(`_raylibr_unload_sound_`, sound))
}

unload_sound_alias_ <- function(alias) {
    invisible(.Call(`_raylibr_unload_sound_alias_`, alias))
}

export_wave_ <- function(wave, file_name) {
    .Call(`_raylibr_export_wave_`, wave, file_name)
}

export_wave_as_code_ <- function(wave, file_name) {
    .Call(`_raylibr_export_wave_as_code_`, wave, file_name)
}

play_sound_ <- function(sound) {
    invisible(.Call(`_raylibr_play_sound_`, sound))
}

stop_sound_ <- function(sound) {
    invisible(.Call(`_raylibr_stop_sound_`, sound))
}

pause_sound_ <- function(sound) {
    invisible(.Call(`_raylibr_pause_sound_`, sound))
}

resume_sound_ <- function(sound) {
    invisible(.Call(`_raylibr_resume_sound_`, sound))
}

is_sound_playing_ <- function(sound) {
    .Call(`_raylibr_is_sound_playing_`, sound)
}

set_sound_volume_ <- function(sound, volume) {
    invisible(.Call(`_raylibr_set_sound_volume_`, sound, volume))
}

set_sound_pitch_ <- function(sound, pitch) {
    invisible(.Call(`_raylibr_set_sound_pitch_`, sound, pitch))
}

load_music_stream_ <- function(file_name) {
    .Call(`_raylibr_load_music_stream_`, file_name)
}

is_music_valid_ <- function(music) {
    .Call(`_raylibr_is_music_valid_`, music)
}

unload_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_unload_music_stream_`, music))
}

play_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_play_music_stream_`, music))
}

is_music_stream_playing_ <- function(music) {
    .Call(`_raylibr_is_music_stream_playing_`, music)
}

update_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_update_music_stream_`, music))
}

stop_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_stop_music_stream_`, music))
}

pause_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_pause_music_stream_`, music))
}

resume_music_stream_ <- function(music) {
    invisible(.Call(`_raylibr_resume_music_stream_`, music))
}

set_music_volume_ <- function(music, volume) {
    invisible(.Call(`_raylibr_set_music_volume_`, music, volume))
}

set_music_pitch_ <- function(music, pitch) {
    invisible(.Call(`_raylibr_set_music_pitch_`, music, pitch))
}

get_music_time_length_ <- function(music) {
    .Call(`_raylibr_get_music_time_length_`, music)
}

get_music_time_played_ <- function(music) {
    .Call(`_raylibr_get_music_time_played_`, music)
}

load_audio_stream_ <- function(sample_rate, sample_size, channels) {
    .Call(`_raylibr_load_audio_stream_`, sample_rate, sample_size, channels)
}

is_audio_stream_valid_ <- function(stream) {
    .Call(`_raylibr_is_audio_stream_valid_`, stream)
}

unload_audio_stream_ <- function(stream) {
    invisible(.Call(`_raylibr_unload_audio_stream_`, stream))
}

is_audio_stream_processed_ <- function(stream) {
    .Call(`_raylibr_is_audio_stream_processed_`, stream)
}

play_audio_stream_ <- function(stream) {
    invisible(.Call(`_raylibr_play_audio_stream_`, stream))
}

pause_audio_stream_ <- function(stream) {
    invisible(.Call(`_raylibr_pause_audio_stream_`, stream))
}

resume_audio_stream_ <- function(stream) {
    invisible(.Call(`_raylibr_resume_audio_stream_`, stream))
}

stop_audio_stream_ <- function(stream) {
    invisible(.Call(`_raylibr_stop_audio_stream_`, stream))
}

set_audio_stream_volume_ <- function(stream, volume) {
    invisible(.Call(`_raylibr_set_audio_stream_volume_`, stream, volume))
}

set_audio_stream_pitch_ <- function(stream, pitch) {
    invisible(.Call(`_raylibr_set_audio_stream_pitch_`, stream, pitch))
}

init_window_ <- function(width, height, title) {
    invisible(.Call(`_raylibr_init_window_`, width, height, title))
}

close_window_ <- function() {
    invisible(.Call(`_raylibr_close_window_`))
}

window_should_close_ <- function() {
    .Call(`_raylibr_window_should_close_`)
}

is_window_ready_ <- function() {
    .Call(`_raylibr_is_window_ready_`)
}

is_window_fullscreen_ <- function() {
    .Call(`_raylibr_is_window_fullscreen_`)
}

is_window_hidden_ <- function() {
    .Call(`_raylibr_is_window_hidden_`)
}

is_window_minimized_ <- function() {
    .Call(`_raylibr_is_window_minimized_`)
}

is_window_maximized_ <- function() {
    .Call(`_raylibr_is_window_maximized_`)
}

is_window_focused_ <- function() {
    .Call(`_raylibr_is_window_focused_`)
}

is_window_resized_ <- function() {
    .Call(`_raylibr_is_window_resized_`)
}

is_window_state_ <- function(flag) {
    .Call(`_raylibr_is_window_state_`, flag)
}

set_window_state_ <- function(flags) {
    invisible(.Call(`_raylibr_set_window_state_`, flags))
}

clear_window_state_ <- function(flags) {
    invisible(.Call(`_raylibr_clear_window_state_`, flags))
}

toggle_fullscreen_ <- function() {
    invisible(.Call(`_raylibr_toggle_fullscreen_`))
}

toggle_borderless_windowed_ <- function() {
    invisible(.Call(`_raylibr_toggle_borderless_windowed_`))
}

maximize_window_ <- function() {
    invisible(.Call(`_raylibr_maximize_window_`))
}

minimize_window_ <- function() {
    invisible(.Call(`_raylibr_minimize_window_`))
}

restore_window_ <- function() {
    invisible(.Call(`_raylibr_restore_window_`))
}

set_window_icon_ <- function(image) {
    invisible(.Call(`_raylibr_set_window_icon_`, image))
}

set_window_title_ <- function(title) {
    invisible(.Call(`_raylibr_set_window_title_`, title))
}

set_window_position_ <- function(x, y) {
    invisible(.Call(`_raylibr_set_window_position_`, x, y))
}

set_window_monitor_ <- function(monitor) {
    invisible(.Call(`_raylibr_set_window_monitor_`, monitor))
}

set_window_size_ <- function(width, height) {
    invisible(.Call(`_raylibr_set_window_size_`, width, height))
}

set_window_opacity_ <- function(opacity) {
    invisible(.Call(`_raylibr_set_window_opacity_`, opacity))
}

set_window_focused_ <- function() {
    invisible(.Call(`_raylibr_set_window_focused_`))
}

get_screen_width_ <- function() {
    .Call(`_raylibr_get_screen_width_`)
}

get_screen_height_ <- function() {
    .Call(`_raylibr_get_screen_height_`)
}

get_render_width_ <- function() {
    .Call(`_raylibr_get_render_width_`)
}

get_render_height_ <- function() {
    .Call(`_raylibr_get_render_height_`)
}

get_monitor_count_ <- function() {
    .Call(`_raylibr_get_monitor_count_`)
}

get_current_monitor_ <- function() {
    .Call(`_raylibr_get_current_monitor_`)
}

get_monitor_position_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_position_`, monitor)
}

get_monitor_width_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_width_`, monitor)
}

get_monitor_height_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_height_`, monitor)
}

get_monitor_physical_width_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_physical_width_`, monitor)
}

get_monitor_physical_height_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_physical_height_`, monitor)
}

get_monitor_refresh_rate_ <- function(monitor) {
    .Call(`_raylibr_get_monitor_refresh_rate_`, monitor)
}

get_window_position_ <- function() {
    .Call(`_raylibr_get_window_position_`)
}

get_window_scale_dpi_ <- function() {
    .Call(`_raylibr_get_window_scale_dpi_`)
}

get_clipboard_image_ <- function() {
    .Call(`_raylibr_get_clipboard_image_`)
}

enable_event_waiting_ <- function() {
    invisible(.Call(`_raylibr_enable_event_waiting_`))
}

disable_event_waiting_ <- function() {
    invisible(.Call(`_raylibr_disable_event_waiting_`))
}

show_cursor_ <- function() {
    invisible(.Call(`_raylibr_show_cursor_`))
}

hide_cursor_ <- function() {
    invisible(.Call(`_raylibr_hide_cursor_`))
}

is_cursor_hidden_ <- function() {
    .Call(`_raylibr_is_cursor_hidden_`)
}

enable_cursor_ <- function() {
    invisible(.Call(`_raylibr_enable_cursor_`))
}

disable_cursor_ <- function() {
    invisible(.Call(`_raylibr_disable_cursor_`))
}

is_cursor_on_screen_ <- function() {
    .Call(`_raylibr_is_cursor_on_screen_`)
}

clear_background_ <- function(color) {
    invisible(.Call(`_raylibr_clear_background_`, color))
}

begin_drawing_ <- function() {
    invisible(.Call(`_raylibr_begin_drawing_`))
}

end_drawing_ <- function() {
    invisible(.Call(`_raylibr_end_drawing_`))
}

begin_mode_2d_ <- function(camera) {
    invisible(.Call(`_raylibr_begin_mode_2d_`, camera))
}

end_mode_2d_ <- function() {
    invisible(.Call(`_raylibr_end_mode_2d_`))
}

begin_mode_3d_ <- function(camera) {
    invisible(.Call(`_raylibr_begin_mode_3d_`, camera))
}

end_mode_3d_ <- function() {
    invisible(.Call(`_raylibr_end_mode_3d_`))
}

begin_shader_mode_ <- function(shader) {
    invisible(.Call(`_raylibr_begin_shader_mode_`, shader))
}

end_shader_mode_ <- function() {
    invisible(.Call(`_raylibr_end_shader_mode_`))
}

begin_blend_mode_ <- function(mode) {
    invisible(.Call(`_raylibr_begin_blend_mode_`, mode))
}

end_blend_mode_ <- function() {
    invisible(.Call(`_raylibr_end_blend_mode_`))
}

begin_scissor_mode_ <- function(x, y, width, height) {
    invisible(.Call(`_raylibr_begin_scissor_mode_`, x, y, width, height))
}

end_scissor_mode_ <- function() {
    invisible(.Call(`_raylibr_end_scissor_mode_`))
}

begin_vr_stereo_mode_ <- function(config) {
    invisible(.Call(`_raylibr_begin_vr_stereo_mode_`, config))
}

end_vr_stereo_mode_ <- function() {
    invisible(.Call(`_raylibr_end_vr_stereo_mode_`))
}

unload_vr_stereo_config_ <- function(config) {
    invisible(.Call(`_raylibr_unload_vr_stereo_config_`, config))
}

load_shader_ <- function(vs_file_name, fs_file_name) {
    .Call(`_raylibr_load_shader_`, vs_file_name, fs_file_name)
}

load_shader_from_memory_ <- function(vs_code, fs_code) {
    .Call(`_raylibr_load_shader_from_memory_`, vs_code, fs_code)
}

is_shader_valid_ <- function(shader) {
    .Call(`_raylibr_is_shader_valid_`, shader)
}

unload_shader_ <- function(shader) {
    invisible(.Call(`_raylibr_unload_shader_`, shader))
}

get_world_to_screen_ <- function(position, camera) {
    .Call(`_raylibr_get_world_to_screen_`, position, camera)
}

get_world_to_screen_ex_ <- function(position, camera, width, height) {
    .Call(`_raylibr_get_world_to_screen_ex_`, position, camera, width, height)
}

get_world_to_screen_2d_ <- function(position, camera) {
    .Call(`_raylibr_get_world_to_screen_2d_`, position, camera)
}

get_screen_to_world_2d_ <- function(position, camera) {
    .Call(`_raylibr_get_screen_to_world_2d_`, position, camera)
}

set_target_fps_ <- function(fps) {
    invisible(.Call(`_raylibr_set_target_fps_`, fps))
}

get_frame_time_ <- function() {
    .Call(`_raylibr_get_frame_time_`)
}

get_time_ <- function() {
    .Call(`_raylibr_get_time_`)
}

get_fps_ <- function() {
    .Call(`_raylibr_get_fps_`)
}

swap_screen_buffer_ <- function() {
    invisible(.Call(`_raylibr_swap_screen_buffer_`))
}

poll_input_events_ <- function() {
    invisible(.Call(`_raylibr_poll_input_events_`))
}

set_random_seed_ <- function(seed) {
    invisible(.Call(`_raylibr_set_random_seed_`, seed))
}

get_random_value_ <- function(min, max) {
    .Call(`_raylibr_get_random_value_`, min, max)
}

take_screenshot_ <- function(file_name) {
    invisible(.Call(`_raylibr_take_screenshot_`, file_name))
}

set_config_flags_ <- function(flags) {
    invisible(.Call(`_raylibr_set_config_flags_`, flags))
}

open_url_ <- function(url) {
    invisible(.Call(`_raylibr_open_url_`, url))
}

set_trace_log_level_ <- function(log_level) {
    invisible(.Call(`_raylibr_set_trace_log_level_`, log_level))
}

load_file_text_ <- function(file_name) {
    .Call(`_raylibr_load_file_text_`, file_name)
}

save_file_text_ <- function(file_name, text) {
    .Call(`_raylibr_save_file_text_`, file_name, text)
}

file_text_find_index_ <- function(file_name, search) {
    .Call(`_raylibr_file_text_find_index_`, file_name, search)
}

file_exists_ <- function(file_name) {
    .Call(`_raylibr_file_exists_`, file_name)
}

directory_exists_ <- function(dir_path) {
    .Call(`_raylibr_directory_exists_`, dir_path)
}

is_file_extension_ <- function(file_name, ext) {
    .Call(`_raylibr_is_file_extension_`, file_name, ext)
}

get_file_length_ <- function(file_name) {
    .Call(`_raylibr_get_file_length_`, file_name)
}

get_file_mod_time_ <- function(file_name) {
    .Call(`_raylibr_get_file_mod_time_`, file_name)
}

get_file_extension_ <- function(file_name) {
    .Call(`_raylibr_get_file_extension_`, file_name)
}

get_file_name_ <- function(file_path) {
    .Call(`_raylibr_get_file_name_`, file_path)
}

get_file_name_without_ext_ <- function(file_path) {
    .Call(`_raylibr_get_file_name_without_ext_`, file_path)
}

get_directory_path_ <- function(file_path) {
    .Call(`_raylibr_get_directory_path_`, file_path)
}

get_prev_directory_path_ <- function(dir_path) {
    .Call(`_raylibr_get_prev_directory_path_`, dir_path)
}

get_working_directory_ <- function() {
    .Call(`_raylibr_get_working_directory_`)
}

get_application_directory_ <- function() {
    .Call(`_raylibr_get_application_directory_`)
}

make_directory_ <- function(dir_path) {
    .Call(`_raylibr_make_directory_`, dir_path)
}

change_directory_ <- function(dir_path) {
    .Call(`_raylibr_change_directory_`, dir_path)
}

is_path_file_ <- function(path) {
    .Call(`_raylibr_is_path_file_`, path)
}

is_file_name_valid_ <- function(file_name) {
    .Call(`_raylibr_is_file_name_valid_`, file_name)
}

is_file_dropped_ <- function() {
    .Call(`_raylibr_is_file_dropped_`)
}

get_directory_file_count_ <- function(dir_path) {
    .Call(`_raylibr_get_directory_file_count_`, dir_path)
}

get_directory_file_count_ex_ <- function(base_path, filter, scan_subdirs) {
    .Call(`_raylibr_get_directory_file_count_ex_`, base_path, filter, scan_subdirs)
}

is_key_pressed_ <- function(key) {
    .Call(`_raylibr_is_key_pressed_`, key)
}

is_key_pressed_repeat_ <- function(key) {
    .Call(`_raylibr_is_key_pressed_repeat_`, key)
}

is_key_down_ <- function(key) {
    .Call(`_raylibr_is_key_down_`, key)
}

is_key_released_ <- function(key) {
    .Call(`_raylibr_is_key_released_`, key)
}

is_key_up_ <- function(key) {
    .Call(`_raylibr_is_key_up_`, key)
}

get_key_pressed_ <- function() {
    .Call(`_raylibr_get_key_pressed_`)
}

set_exit_key_ <- function(key) {
    invisible(.Call(`_raylibr_set_exit_key_`, key))
}

is_gamepad_available_ <- function(gamepad) {
    .Call(`_raylibr_is_gamepad_available_`, gamepad)
}

is_gamepad_button_pressed_ <- function(gamepad, button) {
    .Call(`_raylibr_is_gamepad_button_pressed_`, gamepad, button)
}

is_gamepad_button_down_ <- function(gamepad, button) {
    .Call(`_raylibr_is_gamepad_button_down_`, gamepad, button)
}

is_gamepad_button_released_ <- function(gamepad, button) {
    .Call(`_raylibr_is_gamepad_button_released_`, gamepad, button)
}

is_gamepad_button_up_ <- function(gamepad, button) {
    .Call(`_raylibr_is_gamepad_button_up_`, gamepad, button)
}

get_gamepad_button_pressed_ <- function() {
    .Call(`_raylibr_get_gamepad_button_pressed_`)
}

get_gamepad_axis_count_ <- function(gamepad) {
    .Call(`_raylibr_get_gamepad_axis_count_`, gamepad)
}

get_gamepad_axis_movement_ <- function(gamepad, axis) {
    .Call(`_raylibr_get_gamepad_axis_movement_`, gamepad, axis)
}

set_gamepad_mappings_ <- function(mappings) {
    .Call(`_raylibr_set_gamepad_mappings_`, mappings)
}

set_gamepad_vibration_ <- function(gamepad, left_motor, right_motor, duration) {
    invisible(.Call(`_raylibr_set_gamepad_vibration_`, gamepad, left_motor, right_motor, duration))
}

is_mouse_button_pressed_ <- function(button) {
    .Call(`_raylibr_is_mouse_button_pressed_`, button)
}

is_mouse_button_down_ <- function(button) {
    .Call(`_raylibr_is_mouse_button_down_`, button)
}

is_mouse_button_released_ <- function(button) {
    .Call(`_raylibr_is_mouse_button_released_`, button)
}

is_mouse_button_up_ <- function(button) {
    .Call(`_raylibr_is_mouse_button_up_`, button)
}

get_mouse_x_ <- function() {
    .Call(`_raylibr_get_mouse_x_`)
}

get_mouse_y_ <- function() {
    .Call(`_raylibr_get_mouse_y_`)
}

get_mouse_position_ <- function() {
    .Call(`_raylibr_get_mouse_position_`)
}

get_mouse_delta_ <- function() {
    .Call(`_raylibr_get_mouse_delta_`)
}

set_mouse_position_ <- function(x, y) {
    invisible(.Call(`_raylibr_set_mouse_position_`, x, y))
}

set_mouse_offset_ <- function(offset_x, offset_y) {
    invisible(.Call(`_raylibr_set_mouse_offset_`, offset_x, offset_y))
}

set_mouse_scale_ <- function(scale_x, scale_y) {
    invisible(.Call(`_raylibr_set_mouse_scale_`, scale_x, scale_y))
}

get_mouse_wheel_move_ <- function() {
    .Call(`_raylibr_get_mouse_wheel_move_`)
}

get_mouse_wheel_move_v_ <- function() {
    .Call(`_raylibr_get_mouse_wheel_move_v_`)
}

set_mouse_cursor_ <- function(cursor) {
    invisible(.Call(`_raylibr_set_mouse_cursor_`, cursor))
}

get_touch_x_ <- function() {
    .Call(`_raylibr_get_touch_x_`)
}

get_touch_y_ <- function() {
    .Call(`_raylibr_get_touch_y_`)
}

get_touch_position_ <- function(index) {
    .Call(`_raylibr_get_touch_position_`, index)
}

get_touch_point_id_ <- function(index) {
    .Call(`_raylibr_get_touch_point_id_`, index)
}

get_touch_point_count_ <- function() {
    .Call(`_raylibr_get_touch_point_count_`)
}

set_gestures_enabled_ <- function(flags) {
    invisible(.Call(`_raylibr_set_gestures_enabled_`, flags))
}

is_gesture_detected_ <- function(gesture) {
    .Call(`_raylibr_is_gesture_detected_`, gesture)
}

get_gesture_detected_ <- function() {
    .Call(`_raylibr_get_gesture_detected_`)
}

get_gesture_hold_duration_ <- function() {
    .Call(`_raylibr_get_gesture_hold_duration_`)
}

get_gesture_drag_vector_ <- function() {
    .Call(`_raylibr_get_gesture_drag_vector_`)
}

get_gesture_drag_angle_ <- function() {
    .Call(`_raylibr_get_gesture_drag_angle_`)
}

get_gesture_pinch_vector_ <- function() {
    .Call(`_raylibr_get_gesture_pinch_vector_`)
}

get_gesture_pinch_angle_ <- function() {
    .Call(`_raylibr_get_gesture_pinch_angle_`)
}

get_shapes_texture_ <- function() {
    .Call(`_raylibr_get_shapes_texture_`)
}

get_shapes_texture_rectangle_ <- function() {
    .Call(`_raylibr_get_shapes_texture_rectangle_`)
}

image_text_ <- function(text, font_size, color) {
    .Call(`_raylibr_image_text_`, text, font_size, color)
}

image_text_ex_ <- function(font, text, font_size, spacing, tint) {
    .Call(`_raylibr_image_text_ex_`, font, text, font_size, spacing, tint)
}

fade_ <- function(color, alpha) {
    .Call(`_raylibr_fade_`, color, alpha)
}

get_color_ <- function(hex_value) {
    .Call(`_raylibr_get_color_`, hex_value)
}

get_pixel_data_size_ <- function(width, height, format) {
    .Call(`_raylibr_get_pixel_data_size_`, width, height, format)
}

export_font_as_code_ <- function(font, file_name) {
    .Call(`_raylibr_export_font_as_code_`, font, file_name)
}

set_text_line_spacing_ <- function(spacing) {
    invisible(.Call(`_raylibr_set_text_line_spacing_`, spacing))
}

text_is_equal_ <- function(text1, text2) {
    .Call(`_raylibr_text_is_equal_`, text1, text2)
}

text_length_ <- function(text) {
    .Call(`_raylibr_text_length_`, text)
}

get_text_between_ <- function(text, begin, end) {
    .Call(`_raylibr_get_text_between_`, text, begin, end)
}

text_replace_alloc_ <- function(text, search, replacement) {
    .Call(`_raylibr_text_replace_alloc_`, text, search, replacement)
}

text_replace_between_ <- function(text, begin, end, replacement) {
    .Call(`_raylibr_text_replace_between_`, text, begin, end, replacement)
}

text_replace_between_alloc_ <- function(text, begin, end, replacement) {
    .Call(`_raylibr_text_replace_between_alloc_`, text, begin, end, replacement)
}

text_insert_alloc_ <- function(text, insert, position) {
    .Call(`_raylibr_text_insert_alloc_`, text, insert, position)
}

draw_bounding_box_ <- function(box, color) {
    invisible(.Call(`_raylibr_draw_bounding_box_`, box, color))
}

unload_mesh_ <- function(mesh) {
    invisible(.Call(`_raylibr_unload_mesh_`, mesh))
}

update_model_animation_ <- function(model, anim, frame) {
    invisible(.Call(`_raylibr_update_model_animation_`, model, anim, frame))
}

update_model_animation_ex_ <- function(model, anim_a, frame_a, anim_b, frame_b, blend) {
    invisible(.Call(`_raylibr_update_model_animation_ex_`, model, anim_a, frame_a, anim_b, frame_b, blend))
}

init_audio_device_ <- function() {
    invisible(.Call(`_raylibr_init_audio_device_`))
}

close_audio_device_ <- function() {
    invisible(.Call(`_raylibr_close_audio_device_`))
}

wave_copy_ <- function(wave) {
    .Call(`_raylibr_wave_copy_`, wave)
}

draw_point_3d_ <- function(position, color) {
    invisible(.Call(`_raylibr_draw_point_3d_`, position, color))
}

draw_cube_ <- function(position, width, height, length, color) {
    invisible(.Call(`_raylibr_draw_cube_`, position, width, height, length, color))
}

draw_cube_v_ <- function(position, size, color) {
    invisible(.Call(`_raylibr_draw_cube_v_`, position, size, color))
}

draw_cube_wires_ <- function(position, width, height, length, color) {
    invisible(.Call(`_raylibr_draw_cube_wires_`, position, width, height, length, color))
}

draw_cube_wires_v_ <- function(position, size, color) {
    invisible(.Call(`_raylibr_draw_cube_wires_v_`, position, size, color))
}

draw_sphere_ <- function(center_pos, radius, color) {
    invisible(.Call(`_raylibr_draw_sphere_`, center_pos, radius, color))
}

draw_sphere_ex_ <- function(center_pos, radius, rings, slices, color) {
    invisible(.Call(`_raylibr_draw_sphere_ex_`, center_pos, radius, rings, slices, color))
}

draw_sphere_wires_ <- function(center_pos, radius, rings, slices, color) {
    invisible(.Call(`_raylibr_draw_sphere_wires_`, center_pos, radius, rings, slices, color))
}

draw_cylinder_ <- function(position, radius_top, radius_bottom, height, slices, color) {
    invisible(.Call(`_raylibr_draw_cylinder_`, position, radius_top, radius_bottom, height, slices, color))
}

draw_cylinder_ex_ <- function(start_pos, end_pos, start_radius, end_radius, sides, color) {
    invisible(.Call(`_raylibr_draw_cylinder_ex_`, start_pos, end_pos, start_radius, end_radius, sides, color))
}

draw_cylinder_wires_ <- function(position, radius_top, radius_bottom, height, slices, color) {
    invisible(.Call(`_raylibr_draw_cylinder_wires_`, position, radius_top, radius_bottom, height, slices, color))
}

draw_cylinder_wires_ex_ <- function(start_pos, end_pos, start_radius, end_radius, sides, color) {
    invisible(.Call(`_raylibr_draw_cylinder_wires_ex_`, start_pos, end_pos, start_radius, end_radius, sides, color))
}

draw_capsule_ <- function(start_pos, end_pos, radius, slices, rings, color) {
    invisible(.Call(`_raylibr_draw_capsule_`, start_pos, end_pos, radius, slices, rings, color))
}

draw_capsule_wires_ <- function(start_pos, end_pos, radius, slices, rings, color) {
    invisible(.Call(`_raylibr_draw_capsule_wires_`, start_pos, end_pos, radius, slices, rings, color))
}

draw_plane_ <- function(center_pos, size, color) {
    invisible(.Call(`_raylibr_draw_plane_`, center_pos, size, color))
}

draw_ray_ <- function(ray, color) {
    invisible(.Call(`_raylibr_draw_ray_`, ray, color))
}

draw_grid_ <- function(slices, spacing) {
    invisible(.Call(`_raylibr_draw_grid_`, slices, spacing))
}

load_model_ <- function(file_name) {
    .Call(`_raylibr_load_model_`, file_name)
}

load_model_from_mesh_ <- function(mesh) {
    .Call(`_raylibr_load_model_from_mesh_`, mesh)
}

is_model_valid_ <- function(model) {
    .Call(`_raylibr_is_model_valid_`, model)
}

unload_model_ <- function(model) {
    invisible(.Call(`_raylibr_unload_model_`, model))
}

get_model_bounding_box_ <- function(model) {
    .Call(`_raylibr_get_model_bounding_box_`, model)
}

draw_model_ <- function(model, position, scale, tint) {
    invisible(.Call(`_raylibr_draw_model_`, model, position, scale, tint))
}

draw_model_ex_ <- function(model, position, rotation_axis, rotation_angle, scale, tint) {
    invisible(.Call(`_raylibr_draw_model_ex_`, model, position, rotation_axis, rotation_angle, scale, tint))
}

draw_model_wires_ <- function(model, position, scale, tint) {
    invisible(.Call(`_raylibr_draw_model_wires_`, model, position, scale, tint))
}

draw_model_wires_ex_ <- function(model, position, rotation_axis, rotation_angle, scale, tint) {
    invisible(.Call(`_raylibr_draw_model_wires_ex_`, model, position, rotation_axis, rotation_angle, scale, tint))
}

draw_billboard_ <- function(camera, texture, position, scale, tint) {
    invisible(.Call(`_raylibr_draw_billboard_`, camera, texture, position, scale, tint))
}

draw_billboard_rec_ <- function(camera, texture, source, position, size, tint) {
    invisible(.Call(`_raylibr_draw_billboard_rec_`, camera, texture, source, position, size, tint))
}

draw_billboard_pro_ <- function(camera, texture, source, position, up, size, origin, rotation, tint) {
    invisible(.Call(`_raylibr_draw_billboard_pro_`, camera, texture, source, position, up, size, origin, rotation, tint))
}

draw_mesh_ <- function(mesh, material, transform) {
    invisible(.Call(`_raylibr_draw_mesh_`, mesh, material, transform))
}

load_material_default_ <- function() {
    .Call(`_raylibr_load_material_default_`)
}

is_material_valid_ <- function(material) {
    .Call(`_raylibr_is_material_valid_`, material)
}

unload_material_ <- function(material) {
    invisible(.Call(`_raylibr_unload_material_`, material))
}

is_model_animation_valid_ <- function(model, anim) {
    .Call(`_raylibr_is_model_animation_valid_`, model, anim)
}

get_ray_collision_sphere_ <- function(ray, center, radius) {
    .Call(`_raylibr_get_ray_collision_sphere_`, ray, center, radius)
}

get_ray_collision_box_ <- function(ray, box) {
    .Call(`_raylibr_get_ray_collision_box_`, ray, box)
}

get_ray_collision_mesh_ <- function(ray, mesh, transform) {
    .Call(`_raylibr_get_ray_collision_mesh_`, ray, mesh, transform)
}

get_ray_collision_triangle_ <- function(ray, p1, p2, p3) {
    .Call(`_raylibr_get_ray_collision_triangle_`, ray, p1, p2, p3)
}

get_ray_collision_quad_ <- function(ray, p1, p2, p3, p4) {
    .Call(`_raylibr_get_ray_collision_quad_`, ray, p1, p2, p3, p4)
}

set_shapes_texture_ <- function(texture, source) {
    invisible(.Call(`_raylibr_set_shapes_texture_`, texture, source))
}

draw_pixel_ <- function(pos_x, pos_y, color) {
    invisible(.Call(`_raylibr_draw_pixel_`, pos_x, pos_y, color))
}

draw_pixel_v_ <- function(position, color) {
    invisible(.Call(`_raylibr_draw_pixel_v_`, position, color))
}

draw_line_ <- function(start_pos_x, start_pos_y, end_pos_x, end_pos_y, color) {
    invisible(.Call(`_raylibr_draw_line_`, start_pos_x, start_pos_y, end_pos_x, end_pos_y, color))
}

draw_line_v_ <- function(start_pos, end_pos, color) {
    invisible(.Call(`_raylibr_draw_line_v_`, start_pos, end_pos, color))
}

draw_line_ex_ <- function(start_pos, end_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_ex_`, start_pos, end_pos, thick, color))
}

draw_line_bezier_ <- function(start_pos, end_pos, thick, color) {
    invisible(.Call(`_raylibr_draw_line_bezier_`, start_pos, end_pos, thick, color))
}

draw_line_dashed_ <- function(start_pos, end_pos, dash_size, space_size, color) {
    invisible(.Call(`_raylibr_draw_line_dashed_`, start_pos, end_pos, dash_size, space_size, color))
}

draw_circle_ <- function(center_x, center_y, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_`, center_x, center_y, radius, color))
}

draw_circle_v_ <- function(center, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_v_`, center, radius, color))
}

draw_circle_gradient_ <- function(center, radius, inner, outer) {
    invisible(.Call(`_raylibr_draw_circle_gradient_`, center, radius, inner, outer))
}

draw_circle_sector_ <- function(center, radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_circle_sector_`, center, radius, start_angle, end_angle, segments, color))
}

draw_circle_sector_lines_ <- function(center, radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_circle_sector_lines_`, center, radius, start_angle, end_angle, segments, color))
}

draw_circle_lines_ <- function(center_x, center_y, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_lines_`, center_x, center_y, radius, color))
}

draw_circle_lines_v_ <- function(center, radius, color) {
    invisible(.Call(`_raylibr_draw_circle_lines_v_`, center, radius, color))
}

draw_ellipse_ <- function(center_x, center_y, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse_`, center_x, center_y, radius_h, radius_v, color))
}

draw_ellipse_v_ <- function(center, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse_v_`, center, radius_h, radius_v, color))
}

draw_ellipse_lines_ <- function(center_x, center_y, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse_lines_`, center_x, center_y, radius_h, radius_v, color))
}

draw_ellipse_lines_v_ <- function(center, radius_h, radius_v, color) {
    invisible(.Call(`_raylibr_draw_ellipse_lines_v_`, center, radius_h, radius_v, color))
}

draw_ring_ <- function(center, inner_radius, outer_radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_ring_`, center, inner_radius, outer_radius, start_angle, end_angle, segments, color))
}

draw_ring_lines_ <- function(center, inner_radius, outer_radius, start_angle, end_angle, segments, color) {
    invisible(.Call(`_raylibr_draw_ring_lines_`, center, inner_radius, outer_radius, start_angle, end_angle, segments, color))
}

draw_rectangle_ <- function(pos_x, pos_y, width, height, color) {
    invisible(.Call(`_raylibr_draw_rectangle_`, pos_x, pos_y, width, height, color))
}

draw_rectangle_v_ <- function(position, size, color) {
    invisible(.Call(`_raylibr_draw_rectangle_v_`, position, size, color))
}

draw_rectangle_rec_ <- function(rec, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rec_`, rec, color))
}

draw_rectangle_pro_ <- function(rec, origin, rotation, color) {
    invisible(.Call(`_raylibr_draw_rectangle_pro_`, rec, origin, rotation, color))
}

draw_rectangle_gradient_v_ <- function(pos_x, pos_y, width, height, top, bottom) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_v_`, pos_x, pos_y, width, height, top, bottom))
}

draw_rectangle_gradient_h_ <- function(pos_x, pos_y, width, height, left, right) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_h_`, pos_x, pos_y, width, height, left, right))
}

draw_rectangle_gradient_ex_ <- function(rec, top_left, bottom_left, bottom_right, top_right) {
    invisible(.Call(`_raylibr_draw_rectangle_gradient_ex_`, rec, top_left, bottom_left, bottom_right, top_right))
}

draw_rectangle_lines_ <- function(pos_x, pos_y, width, height, color) {
    invisible(.Call(`_raylibr_draw_rectangle_lines_`, pos_x, pos_y, width, height, color))
}

draw_rectangle_lines_ex_ <- function(rec, line_thick, color) {
    invisible(.Call(`_raylibr_draw_rectangle_lines_ex_`, rec, line_thick, color))
}

draw_rectangle_rounded_ <- function(rec, roundness, segments, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rounded_`, rec, roundness, segments, color))
}

draw_rectangle_rounded_lines_ <- function(rec, roundness, segments, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rounded_lines_`, rec, roundness, segments, color))
}

draw_rectangle_rounded_lines_ex_ <- function(rec, roundness, segments, line_thick, color) {
    invisible(.Call(`_raylibr_draw_rectangle_rounded_lines_ex_`, rec, roundness, segments, line_thick, color))
}

draw_triangle_ <- function(v1, v2, v3, color) {
    invisible(.Call(`_raylibr_draw_triangle_`, v1, v2, v3, color))
}

draw_triangle_lines_ <- function(v1, v2, v3, color) {
    invisible(.Call(`_raylibr_draw_triangle_lines_`, v1, v2, v3, color))
}

draw_poly_ <- function(center, sides, radius, rotation, color) {
    invisible(.Call(`_raylibr_draw_poly_`, center, sides, radius, rotation, color))
}

draw_poly_lines_ <- function(center, sides, radius, rotation, color) {
    invisible(.Call(`_raylibr_draw_poly_lines_`, center, sides, radius, rotation, color))
}

draw_poly_lines_ex_ <- function(center, sides, radius, rotation, line_thick, color) {
    invisible(.Call(`_raylibr_draw_poly_lines_ex_`, center, sides, radius, rotation, line_thick, color))
}

check_collision_recs_ <- function(rec1, rec2) {
    .Call(`_raylibr_check_collision_recs_`, rec1, rec2)
}

check_collision_circles_ <- function(center1, radius1, center2, radius2) {
    .Call(`_raylibr_check_collision_circles_`, center1, radius1, center2, radius2)
}

check_collision_circle_rec_ <- function(center, radius, rec) {
    .Call(`_raylibr_check_collision_circle_rec_`, center, radius, rec)
}

check_collision_point_rec_ <- function(point, rec) {
    .Call(`_raylibr_check_collision_point_rec_`, point, rec)
}

check_collision_point_circle_ <- function(point, center, radius) {
    .Call(`_raylibr_check_collision_point_circle_`, point, center, radius)
}

check_collision_point_triangle_ <- function(point, p1, p2, p3) {
    .Call(`_raylibr_check_collision_point_triangle_`, point, p1, p2, p3)
}

check_collision_point_line_ <- function(point, p1, p2, threshold) {
    .Call(`_raylibr_check_collision_point_line_`, point, p1, p2, threshold)
}

get_collision_rec_ <- function(rec1, rec2) {
    .Call(`_raylibr_get_collision_rec_`, rec1, rec2)
}

draw_line_3d_ <- function(start_pos, end_pos, color) {
    invisible(.Call(`_raylibr_draw_line_3d_`, start_pos, end_pos, color))
}

draw_circle_3d_ <- function(center, radius, rotation_axis, rotation_angle, color) {
    invisible(.Call(`_raylibr_draw_circle_3d_`, center, radius, rotation_axis, rotation_angle, color))
}

draw_triangle_3d_ <- function(v1, v2, v3, color) {
    invisible(.Call(`_raylibr_draw_triangle_3d_`, v1, v2, v3, color))
}

check_collision_spheres_ <- function(center1, radius1, center2, radius2) {
    .Call(`_raylibr_check_collision_spheres_`, center1, radius1, center2, radius2)
}

check_collision_boxes_ <- function(box1, box2) {
    .Call(`_raylibr_check_collision_boxes_`, box1, box2)
}

check_collision_box_sphere_ <- function(box, center, radius) {
    .Call(`_raylibr_check_collision_box_sphere_`, box, center, radius)
}

color_ <- function(r, g, b, a) {
    .Call(`_raylibr_color_`, r, g, b, a)
}

color_get_r_ <- function(obj) {
    .Call(`_raylibr_color_get_r_`, obj)
}

color_set_r_ <- function(obj, r) {
    .Call(`_raylibr_color_set_r_`, obj, r)
}

color_get_g_ <- function(obj) {
    .Call(`_raylibr_color_get_g_`, obj)
}

color_set_g_ <- function(obj, g) {
    .Call(`_raylibr_color_set_g_`, obj, g)
}

color_get_b_ <- function(obj) {
    .Call(`_raylibr_color_get_b_`, obj)
}

color_set_b_ <- function(obj, b) {
    .Call(`_raylibr_color_set_b_`, obj, b)
}

color_get_a_ <- function(obj) {
    .Call(`_raylibr_color_get_a_`, obj)
}

color_set_a_ <- function(obj, a) {
    .Call(`_raylibr_color_set_a_`, obj, a)
}

rectangle_ <- function(x, y, width, height) {
    .Call(`_raylibr_rectangle_`, x, y, width, height)
}

rectangle_get_x_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_x_`, obj)
}

rectangle_set_x_ <- function(obj, x) {
    .Call(`_raylibr_rectangle_set_x_`, obj, x)
}

rectangle_get_y_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_y_`, obj)
}

rectangle_set_y_ <- function(obj, y) {
    .Call(`_raylibr_rectangle_set_y_`, obj, y)
}

rectangle_get_width_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_width_`, obj)
}

rectangle_set_width_ <- function(obj, width) {
    .Call(`_raylibr_rectangle_set_width_`, obj, width)
}

rectangle_get_height_ <- function(obj) {
    .Call(`_raylibr_rectangle_get_height_`, obj)
}

rectangle_set_height_ <- function(obj, height) {
    .Call(`_raylibr_rectangle_set_height_`, obj, height)
}

n_patch_info_ <- function(source, left, top, right, bottom, layout) {
    .Call(`_raylibr_n_patch_info_`, source, left, top, right, bottom, layout)
}

n_patch_info_get_source_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_source_`, obj)
}

n_patch_info_set_source_ <- function(obj, source) {
    .Call(`_raylibr_n_patch_info_set_source_`, obj, source)
}

n_patch_info_get_left_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_left_`, obj)
}

n_patch_info_set_left_ <- function(obj, left) {
    .Call(`_raylibr_n_patch_info_set_left_`, obj, left)
}

n_patch_info_get_top_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_top_`, obj)
}

n_patch_info_set_top_ <- function(obj, top) {
    .Call(`_raylibr_n_patch_info_set_top_`, obj, top)
}

n_patch_info_get_right_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_right_`, obj)
}

n_patch_info_set_right_ <- function(obj, right) {
    .Call(`_raylibr_n_patch_info_set_right_`, obj, right)
}

n_patch_info_get_bottom_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_bottom_`, obj)
}

n_patch_info_set_bottom_ <- function(obj, bottom) {
    .Call(`_raylibr_n_patch_info_set_bottom_`, obj, bottom)
}

n_patch_info_get_layout_ <- function(obj) {
    .Call(`_raylibr_n_patch_info_get_layout_`, obj)
}

n_patch_info_set_layout_ <- function(obj, layout) {
    .Call(`_raylibr_n_patch_info_set_layout_`, obj, layout)
}

glyph_info_ <- function(value, offset_x, offset_y, advance_x, image) {
    .Call(`_raylibr_glyph_info_`, value, offset_x, offset_y, advance_x, image)
}

glyph_info_get_value_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_value_`, obj)
}

glyph_info_set_value_ <- function(obj, value) {
    .Call(`_raylibr_glyph_info_set_value_`, obj, value)
}

glyph_info_get_offset_x_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_offset_x_`, obj)
}

glyph_info_set_offset_x_ <- function(obj, offset_x) {
    .Call(`_raylibr_glyph_info_set_offset_x_`, obj, offset_x)
}

glyph_info_get_offset_y_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_offset_y_`, obj)
}

glyph_info_set_offset_y_ <- function(obj, offset_y) {
    .Call(`_raylibr_glyph_info_set_offset_y_`, obj, offset_y)
}

glyph_info_get_advance_x_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_advance_x_`, obj)
}

glyph_info_set_advance_x_ <- function(obj, advance_x) {
    .Call(`_raylibr_glyph_info_set_advance_x_`, obj, advance_x)
}

glyph_info_get_image_ <- function(obj) {
    .Call(`_raylibr_glyph_info_get_image_`, obj)
}

glyph_info_set_image_ <- function(obj, image) {
    .Call(`_raylibr_glyph_info_set_image_`, obj, image)
}

camera_3d_ <- function(position, target, up, fovy, projection) {
    .Call(`_raylibr_camera_3d_`, position, target, up, fovy, projection)
}

camera_3d_get_position_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_position_`, obj)
}

camera_3d_set_position_ <- function(obj, position) {
    .Call(`_raylibr_camera_3d_set_position_`, obj, position)
}

camera_3d_get_target_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_target_`, obj)
}

camera_3d_set_target_ <- function(obj, target) {
    .Call(`_raylibr_camera_3d_set_target_`, obj, target)
}

camera_3d_get_up_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_up_`, obj)
}

camera_3d_set_up_ <- function(obj, up) {
    .Call(`_raylibr_camera_3d_set_up_`, obj, up)
}

camera_3d_get_fovy_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_fovy_`, obj)
}

camera_3d_set_fovy_ <- function(obj, fovy) {
    .Call(`_raylibr_camera_3d_set_fovy_`, obj, fovy)
}

camera_3d_get_projection_ <- function(obj) {
    .Call(`_raylibr_camera_3d_get_projection_`, obj)
}

camera_3d_set_projection_ <- function(obj, projection) {
    .Call(`_raylibr_camera_3d_set_projection_`, obj, projection)
}

camera_2d_ <- function(offset, target, rotation, zoom) {
    .Call(`_raylibr_camera_2d_`, offset, target, rotation, zoom)
}

camera_2d_get_offset_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_offset_`, obj)
}

camera_2d_set_offset_ <- function(obj, offset) {
    .Call(`_raylibr_camera_2d_set_offset_`, obj, offset)
}

camera_2d_get_target_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_target_`, obj)
}

camera_2d_set_target_ <- function(obj, target) {
    .Call(`_raylibr_camera_2d_set_target_`, obj, target)
}

camera_2d_get_rotation_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_rotation_`, obj)
}

camera_2d_set_rotation_ <- function(obj, rotation) {
    .Call(`_raylibr_camera_2d_set_rotation_`, obj, rotation)
}

camera_2d_get_zoom_ <- function(obj) {
    .Call(`_raylibr_camera_2d_get_zoom_`, obj)
}

camera_2d_set_zoom_ <- function(obj, zoom) {
    .Call(`_raylibr_camera_2d_set_zoom_`, obj, zoom)
}

material_map_ <- function(texture, color, value) {
    .Call(`_raylibr_material_map_`, texture, color, value)
}

material_map_get_texture_ <- function(obj) {
    .Call(`_raylibr_material_map_get_texture_`, obj)
}

material_map_set_texture_ <- function(obj, texture) {
    .Call(`_raylibr_material_map_set_texture_`, obj, texture)
}

material_map_get_color_ <- function(obj) {
    .Call(`_raylibr_material_map_get_color_`, obj)
}

material_map_set_color_ <- function(obj, color) {
    .Call(`_raylibr_material_map_set_color_`, obj, color)
}

material_map_get_value_ <- function(obj) {
    .Call(`_raylibr_material_map_get_value_`, obj)
}

material_map_set_value_ <- function(obj, value) {
    .Call(`_raylibr_material_map_set_value_`, obj, value)
}

transform_ <- function(translation, rotation, scale) {
    .Call(`_raylibr_transform_`, translation, rotation, scale)
}

transform_get_translation_ <- function(obj) {
    .Call(`_raylibr_transform_get_translation_`, obj)
}

transform_set_translation_ <- function(obj, translation) {
    .Call(`_raylibr_transform_set_translation_`, obj, translation)
}

transform_get_rotation_ <- function(obj) {
    .Call(`_raylibr_transform_get_rotation_`, obj)
}

transform_set_rotation_ <- function(obj, rotation) {
    .Call(`_raylibr_transform_set_rotation_`, obj, rotation)
}

transform_get_scale_ <- function(obj) {
    .Call(`_raylibr_transform_get_scale_`, obj)
}

transform_set_scale_ <- function(obj, scale) {
    .Call(`_raylibr_transform_set_scale_`, obj, scale)
}

ray_ <- function(position, direction) {
    .Call(`_raylibr_ray_`, position, direction)
}

ray_get_position_ <- function(obj) {
    .Call(`_raylibr_ray_get_position_`, obj)
}

ray_set_position_ <- function(obj, position) {
    .Call(`_raylibr_ray_set_position_`, obj, position)
}

ray_get_direction_ <- function(obj) {
    .Call(`_raylibr_ray_get_direction_`, obj)
}

ray_set_direction_ <- function(obj, direction) {
    .Call(`_raylibr_ray_set_direction_`, obj, direction)
}

ray_collision_ <- function(hit, distance, point, normal) {
    .Call(`_raylibr_ray_collision_`, hit, distance, point, normal)
}

ray_collision_get_hit_ <- function(obj) {
    .Call(`_raylibr_ray_collision_get_hit_`, obj)
}

ray_collision_set_hit_ <- function(obj, hit) {
    .Call(`_raylibr_ray_collision_set_hit_`, obj, hit)
}

ray_collision_get_distance_ <- function(obj) {
    .Call(`_raylibr_ray_collision_get_distance_`, obj)
}

ray_collision_set_distance_ <- function(obj, distance) {
    .Call(`_raylibr_ray_collision_set_distance_`, obj, distance)
}

ray_collision_get_point_ <- function(obj) {
    .Call(`_raylibr_ray_collision_get_point_`, obj)
}

ray_collision_set_point_ <- function(obj, point) {
    .Call(`_raylibr_ray_collision_set_point_`, obj, point)
}

ray_collision_get_normal_ <- function(obj) {
    .Call(`_raylibr_ray_collision_get_normal_`, obj)
}

ray_collision_set_normal_ <- function(obj, normal) {
    .Call(`_raylibr_ray_collision_set_normal_`, obj, normal)
}

bounding_box_ <- function(min, max) {
    .Call(`_raylibr_bounding_box_`, min, max)
}

bounding_box_get_min_ <- function(obj) {
    .Call(`_raylibr_bounding_box_get_min_`, obj)
}

bounding_box_set_min_ <- function(obj, min) {
    .Call(`_raylibr_bounding_box_set_min_`, obj, min)
}

bounding_box_get_max_ <- function(obj) {
    .Call(`_raylibr_bounding_box_get_max_`, obj)
}

bounding_box_set_max_ <- function(obj, max) {
    .Call(`_raylibr_bounding_box_set_max_`, obj, max)
}

draw_texture_ <- function(texture, pos_x, pos_y, tint) {
    invisible(.Call(`_raylibr_draw_texture_`, texture, pos_x, pos_y, tint))
}

draw_texture_v_ <- function(texture, position, tint) {
    invisible(.Call(`_raylibr_draw_texture_v_`, texture, position, tint))
}

draw_texture_ex_ <- function(texture, position, rotation, scale, tint) {
    invisible(.Call(`_raylibr_draw_texture_ex_`, texture, position, rotation, scale, tint))
}

draw_texture_rec_ <- function(texture, source, position, tint) {
    invisible(.Call(`_raylibr_draw_texture_rec_`, texture, source, position, tint))
}

draw_texture_pro_ <- function(texture, source, dest, origin, rotation, tint) {
    invisible(.Call(`_raylibr_draw_texture_pro_`, texture, source, dest, origin, rotation, tint))
}

draw_texture_n_patch_ <- function(texture, n_patch_info, dest, origin, rotation, tint) {
    invisible(.Call(`_raylibr_draw_texture_n_patch_`, texture, n_patch_info, dest, origin, rotation, tint))
}

get_font_default_ <- function() {
    .Call(`_raylibr_get_font_default_`)
}

load_font_ <- function(file_name) {
    .Call(`_raylibr_load_font_`, file_name)
}

load_font_from_image_ <- function(image, key, first_char) {
    .Call(`_raylibr_load_font_from_image_`, image, key, first_char)
}

is_font_valid_ <- function(font) {
    .Call(`_raylibr_is_font_valid_`, font)
}

unload_font_ <- function(font) {
    invisible(.Call(`_raylibr_unload_font_`, font))
}

draw_fps_ <- function(pos_x, pos_y) {
    invisible(.Call(`_raylibr_draw_fps_`, pos_x, pos_y))
}

draw_text_ <- function(text, pos_x, pos_y, font_size, color) {
    invisible(.Call(`_raylibr_draw_text_`, text, pos_x, pos_y, font_size, color))
}

draw_text_ex_ <- function(font, text, position, font_size, spacing, tint) {
    invisible(.Call(`_raylibr_draw_text_ex_`, font, text, position, font_size, spacing, tint))
}

draw_text_pro_ <- function(font, text, position, origin, rotation, font_size, spacing, tint) {
    invisible(.Call(`_raylibr_draw_text_pro_`, font, text, position, origin, rotation, font_size, spacing, tint))
}

draw_text_codepoint_ <- function(font, codepoint, position, font_size, tint) {
    invisible(.Call(`_raylibr_draw_text_codepoint_`, font, codepoint, position, font_size, tint))
}

measure_text_ <- function(text, font_size) {
    .Call(`_raylibr_measure_text_`, text, font_size)
}

measure_text_ex_ <- function(font, text, font_size, spacing) {
    .Call(`_raylibr_measure_text_ex_`, font, text, font_size, spacing)
}

begin_texture_mode_ <- function(target) {
    invisible(.Call(`_raylibr_begin_texture_mode_`, target))
}

end_texture_mode_ <- function() {
    invisible(.Call(`_raylibr_end_texture_mode_`))
}

load_image_ <- function(file_name) {
    .Call(`_raylibr_load_image_`, file_name)
}

load_image_from_texture_ <- function(texture) {
    .Call(`_raylibr_load_image_from_texture_`, texture)
}

load_image_from_screen_ <- function() {
    .Call(`_raylibr_load_image_from_screen_`)
}

is_image_valid_ <- function(image) {
    .Call(`_raylibr_is_image_valid_`, image)
}

unload_image_ <- function(image) {
    invisible(.Call(`_raylibr_unload_image_`, image))
}

export_image_ <- function(image, file_name) {
    .Call(`_raylibr_export_image_`, image, file_name)
}

export_image_as_code_ <- function(image, file_name) {
    .Call(`_raylibr_export_image_as_code_`, image, file_name)
}

gen_image_color_ <- function(width, height, color) {
    .Call(`_raylibr_gen_image_color_`, width, height, color)
}

gen_image_gradient_linear_ <- function(width, height, direction, start, end) {
    .Call(`_raylibr_gen_image_gradient_linear_`, width, height, direction, start, end)
}

gen_image_gradient_radial_ <- function(width, height, density, inner, outer) {
    .Call(`_raylibr_gen_image_gradient_radial_`, width, height, density, inner, outer)
}

gen_image_gradient_square_ <- function(width, height, density, inner, outer) {
    .Call(`_raylibr_gen_image_gradient_square_`, width, height, density, inner, outer)
}

gen_image_checked_ <- function(width, height, checks_x, checks_y, col1, col2) {
    .Call(`_raylibr_gen_image_checked_`, width, height, checks_x, checks_y, col1, col2)
}

gen_image_white_noise_ <- function(width, height, factor) {
    .Call(`_raylibr_gen_image_white_noise_`, width, height, factor)
}

gen_image_cellular_ <- function(width, height, tile_size) {
    .Call(`_raylibr_gen_image_cellular_`, width, height, tile_size)
}

gen_image_text_ <- function(width, height, text) {
    .Call(`_raylibr_gen_image_text_`, width, height, text)
}

image_copy_ <- function(image) {
    .Call(`_raylibr_image_copy_`, image)
}

image_from_image_ <- function(image, rec) {
    .Call(`_raylibr_image_from_image_`, image, rec)
}

get_image_color_ <- function(image, x, y) {
    .Call(`_raylibr_get_image_color_`, image, x, y)
}

load_texture_ <- function(file_name) {
    .Call(`_raylibr_load_texture_`, file_name)
}

load_texture_from_image_ <- function(image) {
    .Call(`_raylibr_load_texture_from_image_`, image)
}

load_render_texture_ <- function(width, height) {
    .Call(`_raylibr_load_render_texture_`, width, height)
}

is_texture_valid_ <- function(texture) {
    .Call(`_raylibr_is_texture_valid_`, texture)
}

unload_texture_ <- function(texture) {
    invisible(.Call(`_raylibr_unload_texture_`, texture))
}

is_render_texture_valid_ <- function(target) {
    .Call(`_raylibr_is_render_texture_valid_`, target)
}

unload_render_texture_ <- function(target) {
    invisible(.Call(`_raylibr_unload_render_texture_`, target))
}

set_texture_filter_ <- function(texture, filter) {
    invisible(.Call(`_raylibr_set_texture_filter_`, texture, filter))
}

set_texture_wrap_ <- function(texture, wrap) {
    invisible(.Call(`_raylibr_set_texture_wrap_`, texture, wrap))
}

color_to_int_ <- function(color) {
    .Call(`_raylibr_color_to_int_`, color)
}

color_normalize_ <- function(color) {
    .Call(`_raylibr_color_normalize_`, color)
}

color_tint_ <- function(color, tint) {
    .Call(`_raylibr_color_tint_`, color, tint)
}

color_alpha_ <- function(color, alpha) {
    .Call(`_raylibr_color_alpha_`, color, alpha)
}

color_alpha_blend_ <- function(dst, src, tint) {
    .Call(`_raylibr_color_alpha_blend_`, dst, src, tint)
}

color_from_ <- function(x) {
    .Call(`_raylibr_color_from_`, x)
}

set_main_loop_callback_ <- function(update_fn, cleanup_fn) {
    invisible(.Call(`_raylibr_set_main_loop_callback`, update_fn, cleanup_fn))
}

raylib_version_ <- function() {
    .Call(`_raylibr_raylib_version_impl`)
}

is_web_ <- function() {
    .Call(`_raylibr_is_web_impl`)
}

