name: webR build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  webr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build webR package
        uses: r-wasm/actions/build-rwasm@v2
        with:
          packages: "."

      - name: Upload WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: raylibr-wasm
          path: _pkgs/
